import React,{useEffect,useState} from 'react';
import {ContentBlocks,PageBlock} from '../../cabinet/src/public-pages';
type Requester=(path:string,options?:RequestInit)=>Promise<any>;
const blankBlock=(kind:PageBlock['kind']='text'):PageBlock=>({kind,title:'',text:'',label:'',url:'',items:[]});
const blank=()=>({slug:'',locale:'ru',kind:'news',title:'',summary:'',starts_at:'',ends_at:'',blocks:[blankBlock()]});
export function ContentPublishing({request,initialRows}:{request:Requester;initialRows:any[]}){
 const[rows,setRows]=useState(initialRows),[page,setPage]=useState<any>(null),[draft,setDraft]=useState<any>(blank),[history,setHistory]=useState<any[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),[preview,setPreview]=useState(false),[more,setMore]=useState(initialRows.length===50);
 useEffect(()=>{setRows(initialRows);setMore(initialRows.length===50)},[initialRows]);
 function edit(patch:any){setDraft((d:any)=>({...d,...patch}));setDirty(true)}
 function block(i:number,patch:any){edit({blocks:draft.blocks.map((b:PageBlock,j:number)=>j===i?{...b,...patch}:b)})}
 function populate(p:any){setPage(p);setDraft({...p.draft,starts_at:(p.draft.starts_at||'').slice(0,19),ends_at:(p.draft.ends_at||'').slice(0,19)});setDirty(false);setRows(r=>[p,...r.filter(x=>x.id!==p.id)])}
 async function choose(id:number){if(dirty&&!window.confirm('Отменить несохранённые изменения?'))return;setBusy(true);setError('');try{const p=await request(`/api/admin/pages/${id}`);populate(p);setHistory(await request(`/api/admin/pages/${id}/revisions`))}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function run(action:string,revision?:number){setBusy(true);setError('');try{let p;
 if(action==='save'){const data={...draft,starts_at:draft.starts_at?draft.starts_at+'Z':null,ends_at:draft.ends_at?draft.ends_at+'Z':null};p=await request(page?`/api/admin/pages/${page.id}`:'/api/admin/pages',{method:page?'PUT':'POST',body:JSON.stringify({...data,...(page?{version:page.version}:{})})})}
 else p=await request(`/api/admin/pages/${page.id}/${action}`,{method:'POST',body:JSON.stringify({version:page.version,...(revision?{revision}:{})})});
 populate(p);setHistory(await request(`/api/admin/pages/${p.id}/revisions`));
 }catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function loadMore(){setBusy(true);try{const x=await request(`/api/admin/pages?offset=${rows.length}`);setRows(r=>[...r,...x]);setMore(x.length===50)}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <section><p>Черновик публикуется отдельным действием. Изменение черновика не меняет действующую страницу. Текст отображается безопасно; HTML не исполняется.</p>{error&&<p className="error" role="alert">{error}</p>}<div className="btn-row"><button disabled={busy} onClick={()=>{if(dirty&&!window.confirm('Отменить несохранённые изменения?'))return;setPage(null);setDraft(blank());setHistory([]);setDirty(false)}}>Новая страница</button>{rows.map(p=><button disabled={busy} key={p.id} onClick={()=>choose(p.id)}>{p.draft.title} · {p.draft.locale} · {p.archived?'архив':p.published_revision?'опубликовано':'черновик'}</button>)}{more&&<button disabled={busy} onClick={loadMore}>Ещё страницы</button>}</div>
 <fieldset disabled={busy}><legend>{page?`Страница #${page.id}, версия ${page.version}`:'Новая публикация'}</legend><label>Slug<input value={draft.slug} disabled={!!page} onChange={e=>edit({slug:e.target.value})}/></label><label>Язык<select aria-label="Язык" value={draft.locale} disabled={!!page} onChange={e=>edit({locale:e.target.value})}><option value="ru">Русский</option><option value="en">English</option></select></label><label>Тип страницы<select aria-label="Тип страницы" value={draft.kind} disabled={!!page} onChange={e=>edit({kind:e.target.value})}><option value="news">Новость</option><option value="landing">Лендинг</option><option value="legal">Юридическая страница</option></select></label><label>Заголовок<input value={draft.title} onChange={e=>edit({title:e.target.value})}/></label><label>Краткое описание<textarea value={draft.summary} onChange={e=>edit({summary:e.target.value})}/></label><label>Начало публикации (UTC)<input type="datetime-local" step="1" value={draft.starts_at} onChange={e=>edit({starts_at:e.target.value})}/></label><label>Конец публикации (UTC)<input type="datetime-local" step="1" value={draft.ends_at} onChange={e=>edit({ends_at:e.target.value})}/></label>
 {draft.blocks.map((b:PageBlock,i:number)=><fieldset key={i}><legend>Блок {i+1}</legend><label>Тип блока<select aria-label="Тип блока" value={b.kind} onChange={e=>block(i,{...blankBlock(e.target.value as PageBlock['kind']),title:b.title,text:b.text})}><option value="hero">Заглавный блок</option><option value="text">Текст</option><option value="cta">Кнопка</option><option value="features">Преимущества</option><option value="faq">Вопросы и ответы</option></select></label><label>Заголовок блока<input value={b.title} onChange={e=>block(i,{title:e.target.value})}/></label><label>Текст блока<textarea value={b.text} onChange={e=>block(i,{text:e.target.value})}/></label>{b.kind==='cta'&&<><label>Подпись кнопки<input value={b.label} onChange={e=>block(i,{label:e.target.value})}/></label><label>Ссылка кнопки<input value={b.url} onChange={e=>block(i,{url:e.target.value})}/></label></>}{(b.kind==='features'||b.kind==='faq')&&<>{b.items.map((x,j)=><fieldset key={j}><legend>Элемент {j+1}</legend><label>Заголовок элемента<input value={x.title} onChange={e=>block(i,{items:b.items.map((y,k)=>j===k?{...y,title:e.target.value}:y)})}/></label><label>Текст элемента<textarea value={x.text} onChange={e=>block(i,{items:b.items.map((y,k)=>j===k?{...y,text:e.target.value}:y)})}/></label><button onClick={()=>block(i,{items:b.items.filter((_,k)=>k!==j)})}>Удалить элемент</button></fieldset>)}<button disabled={b.items.length>=20} onClick={()=>block(i,{items:[...b.items,{title:'',text:''}]})}>Добавить элемент</button></>}
 <div className="btn-row"><button disabled={!i} onClick={()=>{const x=[...draft.blocks];[x[i-1],x[i]]=[x[i],x[i-1]];edit({blocks:x})}}>Выше</button><button disabled={i===draft.blocks.length-1} onClick={()=>{const x=[...draft.blocks];[x[i+1],x[i]]=[x[i],x[i+1]];edit({blocks:x})}}>Ниже</button><button disabled={draft.blocks.length===1} onClick={()=>edit({blocks:draft.blocks.filter((_:any,j:number)=>i!==j)})}>Удалить блок</button></div></fieldset>)}<button disabled={draft.blocks.length>=30} onClick={()=>edit({blocks:[...draft.blocks,blankBlock()]})}>Добавить блок</button></fieldset>
 <div className="btn-row"><button disabled={busy} onClick={()=>run('save')}>Сохранить черновик</button><button onClick={()=>setPreview(!preview)}>Предпросмотр</button>{page&&<><button disabled={busy||dirty} onClick={()=>run('publish')}>Опубликовать</button><button disabled={busy||dirty||page.archived} onClick={()=>run('archive')}>Снять с публикации</button><button disabled={busy} onClick={()=>choose(page.id)}>Загрузить актуальную версию</button>{page.public_url&&<a href={page.public_url} target="_blank" rel="noopener noreferrer">Публичная страница</a>}</>}</div>{dirty&&<p>Есть несохранённые изменения. Сначала сохраните черновик.</p>}{preview&&<article aria-label="Предпросмотр страницы"><h1>{draft.title}</h1><p>{draft.summary}</p><ContentBlocks blocks={draft.blocks}/></article>}
 {page&&<section><h2>История публикаций</h2>{history.map(r=><div className="card" key={r.version}><b>Версия {r.version}: {r.snapshot.title}</b><p>{r.created_at} · {r.actor}</p><button disabled={busy||dirty} onClick={()=>run('restore',r.version)}>Восстановить в черновик</button><details><summary>Содержимое публикации</summary><ContentBlocks blocks={r.snapshot.blocks}/></details></div>)}</section>}</section>;
}
