import React, {useEffect, useState} from 'react';
type RequestFn = (path: string, options?: RequestInit) => Promise<any>;
const base = '/api/admin/customer-operations';
const labels: Record<string,string> = {create:'Создать',skip:'Пропустить',created:'Создан',skipped:'Пропущен',restrict:'Ограничить',unrestrict:'Восстановить',preview:'Предпросмотр',applied:'Применено',expired:'Истёк',import:'Импорт',bulk:'Массовое действие'};
export function CustomerOperations({request}: {request: RequestFn}) {
 const [file,setFile]=useState<File|null>(null),[schema,setSchema]=useState<Record<string,string[]>>({}),[table,setTable]=useState(''),[telegram,setTelegram]=useState(''),[username,setUsername]=useState(''),[source,setSource]=useState('');
 const [ids,setIds]=useState(''),[action,setAction]=useState('restrict'),[reason,setReason]=useState(''),[preview,setPreview]=useState<any>(null),[result,setResult]=useState<any>(null),[journal,setJournal]=useState<any[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[confirmed,setConfirmed]=useState(false);
 function reset(){setPreview(null);setConfirmed(false);setResult(null)}
 async function run(task:()=>Promise<void>){setBusy(true);setError('');try{await task()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function refresh(){setJournal(await request(base+'/journal'))}
 useEffect(()=>{refresh().catch(e=>setError(e.message))},[]);
 function chooseTable(value:string,tables=schema){setTable(value);const cols=tables[value]||[];setTelegram(cols.includes('telegram_id')?'telegram_id':'');setUsername(cols.includes('username')?'username':'');reset()}
 async function inspect(){if(!file)return;await run(async()=>{reset();const data=await request(base+'/import/inspect',{method:'POST',body:file});setSchema(data.tables);chooseTable(Object.keys(data.tables)[0]||'',data.tables)})}
 async function importPreview(){if(!file)return;await run(async()=>{reset();const params=new URLSearchParams({source,table,telegram_column:telegram});if(username)params.set('username_column',username);setPreview(await request(base+'/import/preview?'+params,{method:'POST',body:file}))})}
 async function bulkPreview(){await run(async()=>{reset();const raw=ids.trim().split(/[\s,;]+/);if(raw.some(s=>!/^\d+$/.test(s)))throw Error('Введите целые ID через пробел или запятую');setPreview(await request(base+'/bulk/preview',{method:'POST',body:JSON.stringify({action,user_ids:raw.map(Number),reason})}))})}
 async function apply(){if(!preview||!confirmed)return;await run(async()=>{const data=await request(base+'/'+preview.id+'/apply',{method:'POST'});setResult(data);setPreview(null);setConfirmed(false);await refresh()})}
 const columns=schema[table]||[];
 return <details className="card"><summary>Импорт пользователей и массовые операции</summary><p>Импорт переносит только Telegram ID и имя. Балансы, подписки, пароли и email не переносятся. Существующие клиенты сохраняются.</p>
 <fieldset disabled={busy}><legend>Импорт users.db</legend><label>Автономный файл SQLite (до 8 МиБ)<input type="file" accept=".db,.sqlite,.sqlite3" onChange={e=>{setFile(e.target.files?.[0]||null);setSchema({});setTable('');reset()}}/></label><button disabled={!file||file.size>8*1024*1024} onClick={inspect}>Прочитать таблицы</button>{file&&file.size>8*1024*1024&&<p role="alert">Файл превышает 8 МиБ</p>}
 {!!Object.keys(schema).length&&<><label>Название источника<input value={source} maxLength={100} onChange={e=>{setSource(e.target.value);reset()}}/></label><label>Таблица<select value={table} onChange={e=>chooseTable(e.target.value)}>{Object.keys(schema).map(t=><option key={t}>{t}</option>)}</select></label><label>Колонка Telegram ID<select value={telegram} onChange={e=>{setTelegram(e.target.value);reset()}}><option value="">Выберите колонку</option>{columns.map(c=><option key={c}>{c}</option>)}</select></label><label>Колонка имени<select value={username} onChange={e=>{setUsername(e.target.value);reset()}}><option value="">Не переносить имя</option>{columns.map(c=><option key={c}>{c}</option>)}</select></label><button disabled={!telegram||!source.trim()} onClick={importPreview}>Предпросмотр импорта</button></>}
 </fieldset><fieldset disabled={busy}><legend>Доступ к магазину</legend><p>Ограничение закрывает доступ к магазину и отзывает сессии. VPN-подписки в Remnawave не отключаются. Восстановление доступа не возвращает старые сессии.</p><label>ID клиентов магазина (до 500)<textarea value={ids} onChange={e=>{setIds(e.target.value);reset()}} placeholder="12, 34, 56"/></label><label>Действие<select value={action} onChange={e=>{setAction(e.target.value);reset()}}><option value="restrict">Ограничить доступ к магазину</option><option value="unrestrict">Восстановить доступ к магазину</option></select></label><label>Причина<input value={reason} maxLength={500} onChange={e=>{setReason(e.target.value);reset()}}/></label><button disabled={!ids.trim()||reason.trim().length<3} onClick={bulkPreview}>Проверить выбранных клиентов</button></fieldset>
 {error&&<p className="error" role="alert">{error}</p>}{busy&&<p role="status">Обработка…</p>}
 {preview&&<div><h3>Предпросмотр: {preview.total} записей</h3><p>Действителен до {new Date(preview.expires_at+'Z').toLocaleTimeString()}. Создать: {preview.rows.filter((r:any)=>r.action==='create').length}; пропустить: {preview.rows.filter((r:any)=>r.action==='skip').length}; изменить доступ: {preview.rows.filter((r:any)=>r.changed).length}.</p><div className="table-wrap" style={{maxHeight:360,overflow:'auto'}}><table><thead><tr><th>ID магазина</th><th>Telegram ID</th><th>Имя</th><th>Действие</th></tr></thead><tbody>{preview.rows.map((r:any,i:number)=><tr key={i}><td>{r.id??r.user_id??'Новый'}</td><td>{r.telegram_id??'—'}</td><td>{r.username||'—'}</td><td>{labels[r.action]}{r.changed===false?' (без изменений)':''}</td></tr>)}</tbody></table></div><label><input type="checkbox" disabled={busy} checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>Проверил список и подтверждаю действие</label><button className="primary" disabled={busy||!confirmed} onClick={apply}>Применить</button></div>}
 {result&&<p role="status">Операция завершена: {result.total} записей. Результат сохранён в журнале.</p>}
 <h3>Мои последние операции</h3><button disabled={busy} onClick={()=>run(refresh)}>Обновить журнал</button><div className="table-wrap"><table><thead><tr><th>Время</th><th>Операция</th><th>Источник / причина</th><th>Статус</th><th>Результат</th></tr></thead><tbody>{journal.map(r=><tr key={r.id}><td>{new Date(r.created_at+'Z').toLocaleString()}</td><td>{labels[r.kind]}</td><td>{r.reason}</td><td>{labels[r.status]}</td><td>{r.total??'—'}{r.result?.rows&&<details><summary>По клиентам</summary>{r.result.rows.map((x:any,i:number)=><div key={i}>#{x.user_id}: {labels[x.action]}{x.changed===false?' (без изменений)':''}</div>)}</details>}</td></tr>)}</tbody></table></div></details>
}
