import React, {useEffect, useRef, useState} from "react";
type RequestFn = (path: string, options?: RequestInit) => Promise<any>;
const date = (v: string) => v ? new Date(v).toLocaleString() : "—";
const status = (v: string) => ({active:"Активна",cancel_scheduled:"Отмена запланирована",expired:"Истекла",fulfilled:"Выдан",paid:"Оплачен",pending:"Ожидается",failed:"Ошибка",completed:"Завершено",open:"Открыто",closed:"Закрыто",requested:"Запрошено"}[v] || v || "—");
export function CustomerDesk({request, initialRows}: {request: RequestFn; initialRows: any[]}) {
 const [rows,setRows]=useState(initialRows),[query,setQuery]=useState(""),[page,setPage]=useState(1),[customer,setCustomer]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const serial=useRef(0);
 useEffect(()=>{setRows(initialRows)},[initialRows]);useEffect(()=>()=>{serial.current++},[]);
 async function search(next=1){const n=++serial.current;setBusy(true);setError("");try{const data=await request(`/api/admin/v41/crm/users?q=${encodeURIComponent(query.trim())}&page=${next}&page_size=50`);if(n!==serial.current)return;setRows(Array.isArray(data)?data:[]);setPage(next);setCustomer(null)}catch(e:any){if(n===serial.current)setError(e.message)}finally{if(n===serial.current)setBusy(false)}}
 async function open(id:number){const n=++serial.current;setBusy(true);setError("");try{const data=await request(`/api/admin/customers/${id}/360`);if(n===serial.current)setCustomer(data)}catch(e:any){if(n===serial.current)setError(e.message)}finally{if(n===serial.current)setBusy(false)}}
 return <div className="customer-desk"><div className="card"><h2>Клиенты магазина</h2><p>Найдите клиента по ID, Telegram ID, имени или email.</p><form className="inline" onSubmit={e=>{e.preventDefault();search()}}><input aria-label="Поиск клиента" value={query} onChange={e=>setQuery(e.target.value)} placeholder="ID, Telegram ID, имя или email"/><button className="primary" disabled={busy}>Найти</button></form>{error&&<p role="alert" className="error">{error}</p>}{busy&&<p role="status">Загрузка данных…</p>}</div>
 {customer?<><div className="card"><div className="toolbar"><div><h2>{customer.user?.username||`Клиент #${customer.user?.id}`}</h2><p>ID {customer.user?.id} · Telegram {customer.user?.telegram_id||"—"} · создан {date(customer.user?.created_at)}</p></div><button onClick={()=>setCustomer(null)}>К списку</button></div><div className="stats"><div className="metric"><span>Подписка</span><strong>{status(customer.subscription?.status)}</strong></div><div className="metric"><span>Окончание</span><strong>{date(customer.subscription?.expires_at)}</strong></div><div className="metric"><span>Платежи</span><strong>{customer.payments?.length||0}</strong></div><div className="metric"><span>Устройства</span><strong>{customer.devices?.length||0}</strong></div></div></div>
 <Records title="Платежи" rows={customer.payments} columns={[["id","№"],["amount","Сумма"],["currency","Валюта"],["status","Оплата"],["fulfillment_status","Выдача"],["created_at","Дата"]]}/>
 <div className="grid2"><Records title="Устройства" rows={customer.devices} columns={[["name","Название"],["status","Статус"],["last_seen_at","Активность"]]}/><Records title="Обращения" rows={customer.tickets} columns={[["subject","Тема"],["status","Статус"],["created_at","Дата"]]}/></div>
 <div className="grid2"><Records title="Возвраты" rows={customer.refunds} columns={[["payment_id","Платёж"],["amount","Сумма"],["status","Статус"]]}/><Records title="Реферальные операции" rows={customer.referrals} columns={[["amount","Сумма"],["kind","Операция"]]}/></div><Records title="Сигналы антифрода" rows={customer.fraud} columns={[["kind","Сигнал"],["score","Оценка"],["status","Статус"]]}/>
 </>:<div className="card table-card"><div className="table-wrap"><table><thead><tr><th>ID</th><th>Имя</th><th>Email</th><th>Telegram</th><th>Автопродление</th><th/></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{x.id}</td><td>{x.username||"—"}</td><td>{x.email||"—"}</td><td>{x.telegram_id||"—"}</td><td>{x.auto_renew?"Включено":"Выключено"}</td><td><button disabled={busy} onClick={()=>open(x.id)}>Открыть</button></td></tr>)}{!rows.length&&<tr><td colSpan={6} className="empty-state">Клиенты не найдены</td></tr>}</tbody></table></div><div className="table-pagination"><button disabled={busy||page===1} onClick={()=>search(page-1)}>Назад</button><span>Страница {page}</span><button disabled={busy||rows.length<50} onClick={()=>search(page+1)}>Далее</button></div></div>}</div>
}
function Records({title,rows=[],columns}:{title:string;rows?:any[];columns:string[][]}){return <div className="card table-card"><h3>{title}</h3><div className="table-wrap"><table><thead><tr>{columns.map(([key,label])=><th key={key}>{label}</th>)}</tr></thead><tbody>{rows.map((x,i)=><tr key={x.id||i}>{columns.map(([key])=><td key={key}>{key.endsWith("_at")?date(x[key]):key.includes("status")?status(x[key]):String(x[key]??"—")}</td>)}</tr>)}{!rows.length&&<tr><td colSpan={columns.length}>Записей пока нет</td></tr>}</tbody></table></div></div>}
