import React, {useEffect, useState} from 'react';

type RequestFn=(path:string,options?:RequestInit)=>Promise<any>;
const ROOT='/api/admin/customer-operations';
const statuses:Record<string,string>={new:'Новый клиент',existing:'Совпадение: данные сохраняются',already_imported:'Уже перенесён',blocked:'Конфликт',preview:'Ожидает применения',applied:'Применён',cancelled:'Отменён',expired:'Истёк'};
const actions:Record<string,string>={revoke_sessions:'Отозвать сессии входа',disable_auto_renew:'Отключить автопродление',notify:'Отправить уведомление в кабинет'};

export function CustomerOperations({request,history=[],reload}:{request:RequestFn;history?:any[];reload:()=>void}) {
 const [historyRows,setHistoryRows]=useState(history);
 useEffect(()=>setHistoryRows(history),[history]);
 async function refreshHistory(){try{setHistoryRows(await request(ROOT+'/import/history'))}catch(e){failure(e)}}
 const [file,setFile]=useState<File|null>(null),[columns,setColumns]=useState<string[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState('');
 const [mapping,setMapping]=useState({namespace:'old-bot',table:'users',telegram_id:'',source_id:'',username:'',balance:'',balance_unit:'decimal',currency:'RUB',credit_balances:false});
 const [preview,setPreview]=useState<any>(null),[accepted,setAccepted]=useState(false);
 const [bulk,setBulk]=useState({ids:'',action:'revoke_sessions',reason:'',title:'',body:''}),[bulkPreview,setBulkPreview]=useState<any>(null),[bulkKey,setBulkKey]=useState(''),[bulkAccepted,setBulkAccepted]=useState(false);
 const failure=(e:any)=>setError(e.status===403?'Раздел доступен только администратору.':e.message||'Не удалось выполнить действие');
 function edit(key:string,value:any){setMapping(old=>({...old,[key]:value}));setPreview(null);setAccepted(false)}
 function editBulk(key:string,value:string){setBulk(old=>({...old,[key]:value}));setBulkPreview(null);setBulkAccepted(false)}
 function form(){const data=new FormData();if(file)data.append('file',file);return data}
 async function inspect(){if(!file)return;setBusy(true);setError('');setPreview(null);try{const data=form();data.append('table',mapping.table);const schema=await request(ROOT+'/import/inspect',{method:'POST',body:data});setColumns(schema.columns);const choose=(...names:string[])=>names.find(name=>schema.columns.includes(name))||'';setMapping(old=>({...old,currency:schema.currency,telegram_id:choose('telegram_id','telegramId','tg_id','user_id'),source_id:choose('id','user_id'),username:choose('username','name'),balance:choose('balance','wallet_balance')}))}catch(e){failure(e)}finally{setBusy(false)}}
 async function makePreview(){setBusy(true);setError('');setResult('');setPreview(null);setAccepted(false);try{const data=form();data.append('mapping',JSON.stringify({...mapping,source_id:mapping.source_id||null,username:mapping.username||null,balance:mapping.balance||null}));setPreview(await request(ROOT+'/import/preview',{method:'POST',body:data}));refreshHistory()}catch(e){failure(e)}finally{setBusy(false)}}
 async function applyImport(){if(!preview||!accepted)return;setBusy(true);setError('');try{const r=await request(ROOT+`/import/${preview.id}/apply`,{method:'POST',body:JSON.stringify({fingerprint:preview.fingerprint})});setResult(`Импорт завершён: создано ${r.created}, сопоставлено ${r.linked_existing}, уже перенесено ${r.already_imported}, зачислено ${r.credited} ${mapping.currency}.`);setPreview(null);setAccepted(false);refreshHistory()}catch(e:any){failure(e);if(e.status===409)setPreview(null)}finally{setBusy(false)}}
 async function cancel(){if(!preview)return;setBusy(true);setError('');try{await request(ROOT+`/import/${preview.id}/cancel`,{method:'POST'});setPreview(null);setAccepted(false);refreshHistory()}catch(e){failure(e)}finally{setBusy(false)}}
 function bulkPayload(){return {user_ids:bulk.ids.split(/[\s,;]+/).filter(Boolean).map(Number),action:bulk.action,reason:bulk.reason,title:bulk.title,body:bulk.body}}
 async function previewBulk(){setBusy(true);setError('');setResult('');setBulkPreview(null);setBulkAccepted(false);try{setBulkPreview(await request(ROOT+'/bulk/preview',{method:'POST',body:JSON.stringify(bulkPayload())}));setBulkKey(crypto.randomUUID())}catch(e){failure(e)}finally{setBusy(false)}}
 async function applyBulk(){if(!bulkPreview||!bulkAccepted)return;setBusy(true);setError('');try{const r=await request(ROOT+'/bulk/apply',{method:'POST',headers:{'Idempotency-Key':bulkKey},body:JSON.stringify({...bulkPayload(),fingerprint:bulkPreview.fingerprint})});setResult(`${actions[r.action]}: обработано клиентов ${r.users}.`);setBulkPreview(null);setBulkAccepted(false);refreshHistory()}catch(e:any){failure(e);if(e.status===409)setBulkPreview(null)}finally{setBusy(false)}}
 function field(key:'telegram_id'|'source_id'|'username'|'balance',label:string,optional=false){return <label>{label}<select aria-label={label} disabled={busy} value={mapping[key]} onChange={e=>edit(key,e.target.value)}><option value=''>{optional?(key==='source_id'?'Telegram ID':'Не переносить'):'Выберите поле'}</option>{columns.map(column=><option key={column} value={column}>{column}</option>)}</select></label>}
 return <div>{error&&<p className='error' role='alert'>{error}</p>}{result&&<p role='status'>{result}</p>}
  <div className='grid2'><section className='card'><h2>Перенос клиентов из users.db</h2><p>Создаёт Telegram-профили и, по вашему выбору, переносит начальный баланс новым клиентам. Совпавшие аккаунты сохраняют свои данные и деньги.</p>
   <label>Snapshot SQLite до 5 МБ<input disabled={busy} type='file' accept='.db,.sqlite,.sqlite3' onChange={e=>{setFile(e.target.files?.[0]||null);setColumns([]);setPreview(null);setAccepted(false)}}/></label>
   <label>Таблица<input disabled={busy} value={mapping.table} onChange={e=>{edit('table',e.target.value);setColumns([])}}/></label><button disabled={busy||!file} onClick={inspect}>Прочитать поля</button>
   {!!columns.length&&<><label>Постоянное имя источника<input disabled={busy} value={mapping.namespace} onChange={e=>edit('namespace',e.target.value)}/><small>Используйте то же имя для повторных выгрузок этого бота.</small></label>
    {field('telegram_id','Telegram ID')}{field('source_id','Постоянный ID строки источника',true)}<p className='muted'>Если ID строки не выбран, используется Telegram ID.</p>{field('username','Имя клиента',true)}{field('balance','Исходный баланс',true)}
    <label>Единицы баланса<select aria-label="Единицы баланса" disabled={busy} value={mapping.balance_unit} onChange={e=>edit('balance_unit',e.target.value)}><option value='decimal'>Основная единица: 12.34</option><option value='minor'>Младшая единица: 1234 = 12.34</option></select></label>
    <label>Валюта<input disabled={busy} maxLength={3} value={mapping.currency} onChange={e=>edit('currency',e.target.value.toUpperCase())}/></label>
    <label className='check'><input disabled={busy||!mapping.balance} type='checkbox' checked={mapping.credit_balances} onChange={e=>edit('credit_balances',e.target.checked)}/>Зачислить исходный баланс только новым клиентам</label>
    <button className='primary' disabled={busy||!mapping.telegram_id} onClick={makePreview}>Проверить перенос</button></>}
  </section><section className='card'><h2>Массовые операции</h2><label>ID клиентов магазина<textarea disabled={busy} placeholder='1, 2, 3' value={bulk.ids} onChange={e=>editBulk('ids',e.target.value)}/></label><p className='muted'>Не более 200 разных ID. Их можно найти в разделе «Клиенты магазина».</p>
   <label>Действие<select aria-label="Действие" disabled={busy} value={bulk.action} onChange={e=>editBulk('action',e.target.value)}>{Object.entries(actions).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>
   <label>Причина<textarea disabled={busy} value={bulk.reason} onChange={e=>editBulk('reason',e.target.value)}/></label>
   {bulk.action==='notify'&&<><label>Заголовок<input disabled={busy} maxLength={255} value={bulk.title} onChange={e=>editBulk('title',e.target.value)}/></label><label>Текст<textarea disabled={busy} maxLength={5000} value={bulk.body} onChange={e=>editBulk('body',e.target.value)}/></label></>}
   <button disabled={busy||!bulk.ids.trim()||bulk.reason.trim().length<3} onClick={previewBulk}>Проверить операцию</button>
   {bulkPreview&&<div><h3>{actions[bulkPreview.action]}</h3><p>Клиентов: {bulkPreview.users}, подписок: {bulkPreview.subscriptions}, сессий: {bulkPreview.sessions}.</p><p>ID: {bulkPreview.user_ids.join(', ')}</p><label className='check'><input disabled={busy} type='checkbox' checked={bulkAccepted} onChange={e=>setBulkAccepted(e.target.checked)}/>Я проверил список и действие</label><button className='primary' disabled={busy||!bulkAccepted} onClick={applyBulk}>Применить операцию</button></div>}
  </section></div>
  {preview&&<section className='card'><h2>Результат проверки импорта</h2><p>Новых: {preview.counts.new}, совпадений: {preview.counts.existing}, уже перенесено: {preview.counts.already_imported}, конфликтов: {preview.counts.blocked}. Зачисление: {preview.total_credit} {mapping.currency}.</p><p>Проверка действует до {new Date(preview.expires_at+'Z').toLocaleString()}.</p>
   <div className='table-wrap' style={{maxHeight:500,overflow:'auto'}}><table><thead><tr><th>ID источника</th><th>Telegram</th><th>Имя</th><th>Результат</th><th>Зачисление</th></tr></thead><tbody>{preview.rows.map((row:any)=><tr key={row.source_id}><td>{row.source_id}</td><td>{row.telegram_id}</td><td>{row.username||'—'}</td><td>{statuses[row.status]}</td><td>{row.credit}</td></tr>)}</tbody></table></div>
   <label className='check'><input disabled={busy} type='checkbox' checked={accepted} onChange={e=>setAccepted(e.target.checked)}/>Я проверил все строки, валюту и достоверность исходного остатка</label><div className='inline'><button className='primary' disabled={busy||!accepted||preview.counts.blocked>0} onClick={applyImport}>Применить перенос</button><button disabled={busy} onClick={cancel}>Отменить preview</button></div>
  </section>}
  <section className='card'><h2>История импорта</h2><div className='table-wrap'><table><thead><tr><th>Источник</th><th>Статус</th><th>Создано</th><th>Результат</th></tr></thead><tbody>{historyRows.map(row=><tr key={row.id}><td>{row.namespace}<details><summary>SHA256 snapshot</summary><code>{row.source_sha256}</code></details></td><td>{statuses[row.status]||row.status}</td><td>{new Date(row.created_at+'Z').toLocaleString()}</td><td>{row.result?`Новых: ${row.result.created}, сопоставлено: ${row.result.linked_existing}, зачислено: ${row.result.credited}`:'—'}</td></tr>)}{!historyRows.length&&<tr><td colSpan={4}>Импортов пока нет</td></tr>}</tbody></table></div></section>
 </div>;
}
