import React, {useEffect,useRef,useState} from 'react';
type RequestFn=(path:string,options?:RequestInit)=>Promise<any>;
function localDate(d:Date){return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)}
const blank=()=>({title:'',description:'',kind:'contest',starts_at:localDate(new Date()),ends_at:localDate(new Date(Date.now()+86400000)),max_entries:1000,winners_count:1,require_subscription:false,prizes:[{amount:'10',weight:1}]});
const labels:Record<string,string>={draft:'Черновик',open:'Открыта',scheduled:'Запланирована',ended:'Ожидает розыгрыша / завершена',full:'Лимит участников',closed:'Закрыта',drawn:'Розыгрыш завершён'};

export function AdminGiveaways({rows:initial,request,reload}:{rows:any[];request:RequestFn;reload:()=>Promise<void>}) {
 const [rows,setRows]=useState(initial),[more,setMore]=useState(initial.length===200),[form,setForm]=useState(blank),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [entries,setEntries]=useState<any[]>([]),[entryCampaign,setEntryCampaign]=useState<number|null>(null),[next,setNext]=useState<number|null>(null);
 const lock=useRef(false),serial=useRef(0);useEffect(()=>{setRows(initial);setMore(initial.length===200)},[initial]);
 const set=(key:string,value:any)=>setForm(prev=>({...prev,[key]:value}));
 async function run(path:string,method='POST',body?:any){if(lock.current)return false;lock.current=true;setBusy(true);setError('');try{await request(path,{method,body:body===undefined?undefined:JSON.stringify(body)});await reload();return true}catch(e:any){setError(e.message);return false}finally{lock.current=false;setBusy(false)}}
 async function save(e:React.FormEvent){e.preventDefault();let payload:any;try{payload={...form,winners_count:form.kind==='wheel'?1:form.winners_count,starts_at:new Date(form.starts_at).toISOString(),ends_at:new Date(form.ends_at).toISOString(),prizes:form.kind==='contest'?[{amount:form.prizes[0].amount,weight:1}]:form.prizes}}catch{setError('Укажите корректные даты');return}if(await run('/api/admin/giveaways','POST',payload))setForm(blank())}
 async function older(){setBusy(true);setError('');try{const data=await request('/api/admin/giveaways?before='+rows[rows.length-1].id);setRows(prev=>[...prev,...data]);setMore(data.length===200)}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function participants(id:number,after=0){const n=++serial.current;setBusy(true);setError('');if(!after){setEntryCampaign(id);setEntries([]);setNext(null)}try{const d=await request(`/api/admin/giveaways/${id}/entries?after=${after}`);if(n===serial.current){setEntries(prev=>after?[...prev,...d.items]:d.items);setNext(d.next_after)}}catch(e:any){if(n===serial.current)setError(e.message)}finally{if(n===serial.current)setBusy(false)}}
 const budget=form.kind==='contest'?Number(form.prizes[0].amount)*form.winners_count:Math.max(...form.prizes.map(p=>Number(p.amount)))*form.max_entries;
 return <div className="stack">{error&&<p className="error" role="alert">{error}</p>}<div className="card"><h2>Конкурсы и колесо призов</h2><p>Бесплатное участие, один раз на подтверждённый email-аккаунт. После публикации условия неизменяемы. Бюджет — верхний предел бонусов магазина; награды не являются списанием с кассы.</p>
 <form className="form" onSubmit={save}><label>Название<input required maxLength={255} value={form.title} onChange={e=>set('title',e.target.value)}/></label><label>Описание<textarea maxLength={4000} value={form.description} onChange={e=>set('description',e.target.value)}/></label>
 <label>Механика<select value={form.kind} onChange={e=>{set('kind',e.target.value);set('prizes',[{amount:'10',weight:1}]);set('winners_count',1)}}><option value="contest">Конкурс</option><option value="wheel">Колесо призов</option></select></label>
 <label>Начало (ваш часовой пояс)<input required type="datetime-local" value={form.starts_at} onChange={e=>set('starts_at',e.target.value)}/></label><label>Окончание (ваш часовой пояс)<input required type="datetime-local" value={form.ends_at} onChange={e=>set('ends_at',e.target.value)}/></label>
 <label>Лимит участников<input type="number" required min={1} max={10000} value={form.max_entries} onChange={e=>set('max_entries',Number(e.target.value))}/></label>{form.kind==='contest'&&<label>Число победителей<input type="number" required min={1} max={100} value={form.winners_count} onChange={e=>set('winners_count',Number(e.target.value))}/></label>}
 <label><input type="checkbox" checked={form.require_subscription} onChange={e=>set('require_subscription',e.target.checked)}/>Нужна действующая подписка</label>
 {form.prizes.map((p,i)=><fieldset key={i}><legend>Награда {i+1}</legend><label>Сумма на баланс<input required type="number" min={form.kind==='contest'?'0.01':'0'} max={10000} step="0.01" value={p.amount} onChange={e=>set('prizes',form.prizes.map((x,j)=>j===i?{...x,amount:e.target.value}:x))}/></label>{form.kind==='wheel'&&<><label>Вес вероятности<input required type="number" min={1} max={10000} value={p.weight} onChange={e=>set('prizes',form.prizes.map((x,j)=>j===i?{...x,weight:Number(e.target.value)}:x))}/></label>{form.prizes.length>1&&<button type="button" onClick={()=>set('prizes',form.prizes.filter((_,j)=>j!==i))}>Убрать награду</button>}</>}</fieldset>)}
 {form.kind==='wheel'&&form.prizes.length<20&&<button type="button" onClick={()=>set('prizes',[...form.prizes,{amount:'0',weight:1}])}>Добавить награду / пустой сектор</button>}<p>Максимальный бюджет: {budget.toFixed(2)}, не более 1 000 000 в валюте магазина.</p><button className="primary" disabled={busy}>Создать черновик</button></form></div>
 {!rows.length&&<p>Акций пока нет.</p>}{rows.map(row=><article className="card" key={row.id}><h3>#{row.id} · {row.title}</h3><p>{row.kind==='contest'?'Конкурс':'Колесо'} · {labels[row.phase]||row.phase} · {row.entry_count}/{row.max_entries} участников</p><p>Бюджет начислен: {row.budget_credited}/{row.budget_limit} {row.currency}. Окончание: {new Date(row.ends_at).toLocaleString()}</p><div className="inline">
 {row.state==='draft'&&<><button disabled={busy} onClick={()=>confirm(`Опубликовать неизменяемые условия с бюджетом ${row.budget_limit} ${row.currency}?`)&&run(`/api/admin/giveaways/${row.id}/publish`)}>Опубликовать</button><button disabled={busy} onClick={()=>confirm('Удалить черновик?')&&run(`/api/admin/giveaways/${row.id}`,'DELETE')}>Удалить</button></>}
 {row.state==='published'&&<button disabled={busy} onClick={()=>confirm('Закрыть акцию без розыгрыша? Уже начисленные бонусы сохраняются.')&&run(`/api/admin/giveaways/${row.id}/close`)}>Закрыть без розыгрыша</button>}
 {row.kind==='contest'&&row.state==='published'&&row.phase==='ended'&&<button disabled={busy} onClick={()=>confirm('Провести единственный розыгрыш и начислить награды?')&&run(`/api/admin/giveaways/${row.id}/draw`)}>Разыграть призы</button>}
 <button disabled={busy} onClick={()=>participants(row.id)}>Участники и результаты</button></div></article>)}{more&&<button disabled={busy} onClick={older}>Предыдущие акции</button>}
 {entryCampaign!=null&&<div className="card"><h3>Участие в акции №{entryCampaign}</h3>{!entries.length&&!busy&&<p>Участников пока нет.</p>}{entries.map(e=><p key={e.id}>Участие #{e.id} · {e.user_id==null?'аккаунт обезличен':`клиент #${e.user_id}`} · {e.outcome} · {e.reward_amount}</p>)}{next!=null&&<button disabled={busy} onClick={()=>participants(entryCampaign,next)}>Ещё участники</button>}</div>}
 </div>
}
