import React,{useEffect,useState} from 'react';
import {ButtonTree} from '../../cabinet/src/button-tree';
type Req=(path:string,options?:RequestInit)=>Promise<any>;
const styles:Record<string,string>={default:'Обычный',primary:'Синий',success:'Зелёный',danger:'Красный'};
const blankBot=()=>({title:'',action:'',item_type:'folder',parent_id:'',sort_order:0,enabled:true,style:'default',icon_custom_emoji_id:'',icon:''});
const miniNode=()=>({id:crypto.randomUUID(),title:'Новая кнопка',type:'folder',style:'default',icon_custom_emoji_id:'',icon:'',url:'',code:'',field_key:'',children:[]});
const decorate=(nodes:any[],path=''):any[]=>nodes.map((n,i)=>({...miniNode(),...n,id:n.id||`legacy-${path}-${i}`,children:decorate(n.children||[],`${path}-${i}`)}));
const flatten=(nodes:any[]):any[]=>nodes.flatMap(n=>[n,...flatten(n.children||[])]);
function update(nodes:any[],id:string,fn:(node:any)=>any):any[]{return nodes.map(n=>n.id===id?fn(n):{...n,children:update(n.children||[],id,fn)}).filter(Boolean)}
export function MenuTreeEditor({request,data,assetBase=''}:{request:Req;data:any;assetBase?:string}){
 const[rows,setRows]=useState<any[]>(data.menu||[]),[bot,setBot]=useState<any>(blankBot),[buttons,setButtons]=useState<any[]>(decorate(data.settings?.miniapp_buttons||[])),[fingerprint,setFingerprint]=useState(data.miniapp_buttons_fingerprint||''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 useEffect(()=>{setRows(data.menu||[]);setButtons(decorate(data.settings?.miniapp_buttons||[]));setFingerprint(data.miniapp_buttons_fingerprint||'')},[data]);
 async function refresh(){const x=await request('/api/admin/content');setRows(x.menu)}
 async function saveBot(){setBusy(true);setError('');setMessage('');try{const payload={...bot,parent_id:bot.parent_id?Number(bot.parent_id):null,sort_order:Number(bot.sort_order),icon_custom_emoji_id:bot.icon_custom_emoji_id||null};await request(bot.id?`/api/admin/menu/${bot.id}`:'/api/admin/menu',{method:bot.id?'PUT':'POST',body:JSON.stringify(payload)});await refresh();setBot(blankBot());setMessage('Кнопка сохранена')}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function removeBot(){setBusy(true);setError('');try{await request(`/api/admin/menu/${bot.id}`,{method:'DELETE'});await refresh();setBot(blankBot())}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function reloadMini(){if(!window.confirm('Загрузить сохранённое меню? Несохранённые изменения будут потеряны.'))return;setBusy(true);setError('');try{const x=await request('/api/admin/content');setButtons(decorate(x.settings?.miniapp_buttons||[]));setFingerprint(x.miniapp_buttons_fingerprint);setMessage('Загружено актуальное меню')}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function saveMini(){setBusy(true);setError('');setMessage('');try{const clean=(nodes:any[]):any[]=>nodes.map(n=>({...n,icon_custom_emoji_id:n.icon_custom_emoji_id||null,children:clean(n.children||[])}));const x=await request('/api/admin/miniapp/menu',{method:'PUT',body:JSON.stringify({fingerprint,buttons:clean(buttons)})});setButtons(x.buttons);setFingerprint(x.fingerprint);setMessage('Меню приложения сохранено')}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 const all=flatten(buttons);
 function move(id:string,parentId:string){const node=all.find(n=>n.id===id);if(!node)return;const cleaned=update(buttons,id,()=>null);setButtons(parentId?update(cleaned,parentId,p=>({...p,children:[...(p.children||[]),node]})):[...cleaned,node])}
 function miniFields(nodes:any[],depth=1):React.ReactNode{return nodes.map((node:any)=><fieldset key={node.id}><legend>Уровень {depth}: {node.title}</legend><label>Название кнопки<input value={node.title} onChange={e=>setButtons(update(buttons,node.id,n=>({...n,title:e.target.value})))}/></label><label>Действие кнопки<select aria-label={`Действие ${node.id}`} value={node.type} onChange={e=>setButtons(update(buttons,node.id,n=>({...n,type:e.target.value})))}>{['folder','plans','url','promo','field'].map(t=><option key={t} disabled={t!=='folder'&&!!node.children?.length} value={t}>{t==='folder'?'Папка':t==='plans'?'Тарифы':t==='url'?'HTTPS ссылка':t==='promo'?'Промокод':'Поле'}</option>)}</select></label><label>Стиль кнопки<select aria-label={`Стиль ${node.id}`} value={node.style} onChange={e=>setButtons(update(buttons,node.id,n=>({...n,style:e.target.value})))}>{Object.entries(styles).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Custom emoji ID<input value={node.icon_custom_emoji_id||''} onChange={e=>setButtons(update(buttons,node.id,n=>({...n,icon_custom_emoji_id:e.target.value})))}/></label><label>Обычная иконка<input maxLength={16} value={node.icon||''} onChange={e=>setButtons(update(buttons,node.id,n=>({...n,icon:e.target.value})))}/></label>{node.type==='url'&&<label>HTTPS ссылка<input value={node.url} onChange={e=>setButtons(update(buttons,node.id,n=>({...n,url:e.target.value})))}/></label>}{node.type==='promo'&&<label>Промокод кнопки<input value={node.code} onChange={e=>setButtons(update(buttons,node.id,n=>({...n,code:e.target.value})))}/></label>}{node.type==='field'&&<label>Ключ поля<input value={node.field_key} onChange={e=>setButtons(update(buttons,node.id,n=>({...n,field_key:e.target.value})))}/></label>}<label>Перенести в папку<select aria-label={`Перенести ${node.id}`} value="choose" onChange={e=>{if(e.target.value!=='choose')move(node.id,e.target.value)}}><option value="choose">Выберите новое место</option><option value="">В корень</option>{all.filter(n=>n.type==='folder'&&!flatten([node]).some(x=>x.id===n.id)).map(n=><option key={n.id} value={n.id}>{n.title}</option>)}</select></label><button onClick={()=>setButtons(update(buttons,node.id,()=>null))}>Удалить кнопку и её подменю</button>{node.type==='folder'&&<><button disabled={depth>=4||all.length>=30} onClick={()=>setButtons(update(buttons,node.id,n=>({...n,children:[...(n.children||[]),miniNode()]})))}>Добавить дочернюю кнопку</button>{miniFields(node.children||[],depth+1)}</>}</fieldset>)}
 return <section><p>Не более 30 кнопок и четырёх уровней. Telegram поддерживает styles и custom emoji при правах бота; Mini App показывает безопасную статическую миниатюру emoji, а при недоступности — обычную иконку.</p>{error&&<p role="alert" className="error">{error}</p>}{message&&<p role="status">{message}</p>}<section className="card"><h2>Дерево Telegram-меню</h2><div className="btn-row"><button disabled={busy} onClick={()=>setBot(blankBot())}>Новая кнопка бота</button>{rows.map(r=><button disabled={busy} key={r.id} onClick={()=>setBot({...r,parent_id:r.parent_id||'',icon_custom_emoji_id:r.icon_custom_emoji_id||''})}>#{r.id} {r.title} {r.parent_id?`→ #${r.parent_id}`:'(корень)'} {r.enabled?'':'(выключена)'}</button>)}</div><fieldset disabled={busy}><label>Название кнопки бота<input value={bot.title} onChange={e=>setBot({...bot,title:e.target.value})}/></label><label>Тип кнопки бота<select aria-label="Тип кнопки бота" value={bot.item_type} onChange={e=>setBot({...bot,item_type:e.target.value})}><option value="folder">Папка</option><option value="webapp">Mini App</option><option value="url">HTTPS ссылка</option><option value="field">Поле</option></select></label><label>Родитель бота<select aria-label="Родитель бота" value={bot.parent_id} onChange={e=>setBot({...bot,parent_id:e.target.value})}><option value="">Корень</option>{rows.filter(r=>r.item_type==='folder'&&r.id!==bot.id).map(r=><option key={r.id} value={r.id}>#{r.id} {r.title}</option>)}</select></label>{bot.item_type!=='folder'&&<label>URL или ключ поля<input value={bot.action} onChange={e=>setBot({...bot,action:e.target.value})}/></label>}<label>Порядок бота<input type="number" value={bot.sort_order} onChange={e=>setBot({...bot,sort_order:e.target.value})}/></label><label>Стиль бота<select aria-label="Стиль бота" value={bot.style} onChange={e=>setBot({...bot,style:e.target.value})}>{Object.entries(styles).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Emoji ID бота<input value={bot.icon_custom_emoji_id} onChange={e=>setBot({...bot,icon_custom_emoji_id:e.target.value})}/></label><label>Обычная иконка бота<input maxLength={16} value={bot.icon} onChange={e=>setBot({...bot,icon:e.target.value})}/></label><label><input type="checkbox" checked={bot.enabled} onChange={e=>setBot({...bot,enabled:e.target.checked})}/>Кнопка бота включена</label><button onClick={saveBot}>Сохранить кнопку бота</button>{bot.id&&<button onClick={removeBot}>Удалить кнопку бота</button>}</fieldset></section>
 <section className="card"><h2>Дерево Mini App</h2><fieldset disabled={busy}>{miniFields(buttons)}<button disabled={all.length>=30} onClick={()=>setButtons([...buttons,miniNode()])}>Добавить корневую кнопку</button><button onClick={saveMini}>Сохранить меню приложения</button><button onClick={reloadMini}>Загрузить актуальное меню</button></fieldset><h3>Предпросмотр меню</h3><ButtonTree buttons={buttons} run={n=>setMessage(`Действие: ${n.type} — ${n.url||n.code||n.field_key||'Тарифы'}`)} request={request} assetBase={assetBase}/></section></section>;
}
