import React,{useEffect,useState} from 'react';
type Requester=(path:string,options?:RequestInit)=>Promise<any>;
const segments:Record<string,string>={manual:'Ручной список',new:'Без покупок',active:'Активная подписка',expired:'Истёкшая подписка',referred:'Приглашённые'};
const ids=(value:string)=>value.split(/[\s,;]+/).filter(Boolean).map(Number);
export function PromoAudiences({request,data}:{request:Requester;data:any}){
 const[codes,setCodes]=useState<any[]>(data.promo_codes||[]);
 const[groups,setGroups]=useState<any[]>(data.groups||[]),[audiences,setAudiences]=useState<any[]>(data.audiences||[]),[group,setGroup]=useState<any>({name:'',segment:'manual',ids:'',enabled:true}),[offer,setOffer]=useState<any>({promo_id:'',title:'',description:'',scope:'personal',group_id:'',ids:'',enabled:true,version:0,create:true,code:'',kind:'percent',value:'10'}),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{setCodes(data.promo_codes||[]);setGroups(data.groups||[]);setAudiences(data.audiences||[])},[data]);
 async function saveGroup(){setBusy(true);setError('');try{const g=await request(group.id?`/api/admin/promo-groups/${group.id}`:'/api/admin/promo-groups',{method:group.id?'PUT':'POST',body:JSON.stringify({name:group.name,segment:group.segment,user_ids:group.segment==='manual'?ids(group.ids):[],enabled:group.enabled,...(group.id?{version:group.version}:{})})});setGroups(rows=>[g,...rows.filter(x=>x.id!==g.id)]);setGroup({...g,ids:g.user_ids.join(', ')})}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function saveOffer(){setBusy(true);setError('');try{const a=await request(offer.create?'/api/admin/personal-offers':`/api/admin/promo-audiences/${offer.promo_id}`,{method:offer.create?'POST':'PUT',body:JSON.stringify({... (offer.create?{code:offer.code,kind:offer.kind,value:offer.value}:{}),title:offer.title,description:offer.description,version:offer.version,enabled:offer.enabled,group_id:offer.scope==='group'?Number(offer.group_id):null,user_ids:offer.scope==='personal'?ids(offer.ids):[]})});if(a.code)setCodes(rows=>[{id:a.promo_id,code:a.code},...rows.filter(x=>x.id!==a.promo_id)]);setAudiences(rows=>[a,...rows.filter(x=>x.promo_id!==a.promo_id)]);setOffer({...a,scope:a.group_id?'group':'personal',ids:a.user_ids.join(', ')})}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <section>{error&&<p role="alert" className="error">{error}</p>}<p>Новый персональный промокод и его аудитория создаются атомарно. Можно также ограничить аудиторию существующего промокода. Ограничение проверяется при расчёте и резервировании скидки. Отключение оффера блокирует его промокод, сохраняя историю.</p><div className="grid2"><section className="card"><h2>Промогруппы</h2><button disabled={busy} onClick={()=>setGroup({name:'',segment:'manual',ids:'',enabled:true})}>Новая группа</button>{groups.map(g=><button key={g.id} disabled={busy} onClick={()=>setGroup({...g,ids:g.user_ids.join(', ')})}>{g.name} · {segments[g.segment]} · v{g.version}</button>)}<fieldset disabled={busy}><label>Название группы<input value={group.name} onChange={e=>setGroup({...group,name:e.target.value})}/></label><label>Сегмент<select aria-label="Сегмент" value={group.segment} onChange={e=>setGroup({...group,segment:e.target.value})}>{Object.entries(segments).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></label>{group.segment==='manual'&&<label>ID участников<textarea value={group.ids} onChange={e=>setGroup({...group,ids:e.target.value})}/></label>}<label><input type="checkbox" checked={group.enabled} onChange={e=>setGroup({...group,enabled:e.target.checked})}/>Группа включена</label><button onClick={saveGroup}>Сохранить группу</button></fieldset></section>
 <section className="card"><h2>Персональные предложения</h2>{audiences.map(a=><button disabled={busy} key={a.promo_id} onClick={()=>setOffer({...a,scope:a.group_id?'group':'personal',ids:a.user_ids.join(', ')})}>{a.title} · {a.enabled?'включено':'отключено'} · v{a.version}</button>)}<fieldset disabled={busy}><label><input type="checkbox" checked={!!offer.create} onChange={e=>setOffer({...offer,create:e.target.checked,version:0})}/>Создать новый персональный промокод</label>{offer.create&&<><label>Код предложения<input value={offer.code||''} onChange={e=>setOffer({...offer,code:e.target.value.toUpperCase()})}/></label><label>Размер скидки<input type="number" value={offer.value||'10'} onChange={e=>setOffer({...offer,value:e.target.value})}/></label><label>Вид скидки<select aria-label="Вид скидки" value={offer.kind||'percent'} onChange={e=>setOffer({...offer,kind:e.target.value})}><option value="percent">Процент</option><option value="fixed">Фиксированная сумма</option></select></label></>}<label>Промокод<select disabled={!!offer.create} aria-label="Промокод" value={offer.promo_id} onChange={e=>{const a=audiences.find(x=>x.promo_id===Number(e.target.value));setOffer(a?{...a,scope:a.group_id?'group':'personal',ids:a.user_ids.join(', ')}:{promo_id:Number(e.target.value),title:'',description:'',scope:'personal',group_id:'',ids:'',enabled:true,version:0})}}><option value="">Выберите</option>{codes.map((p:any)=><option key={p.id} value={p.id}>{p.code}</option>)}</select></label><label>Название предложения<input value={offer.title} onChange={e=>setOffer({...offer,title:e.target.value})}/></label><label>Описание предложения<textarea value={offer.description} onChange={e=>setOffer({...offer,description:e.target.value})}/></label><label>Аудитория<select aria-label="Аудитория" value={offer.scope} onChange={e=>setOffer({...offer,scope:e.target.value})}><option value="personal">Персональные ID</option><option value="group">Промогруппа</option></select></label>{offer.scope==='personal'?<label>ID получателей<textarea value={offer.ids} onChange={e=>setOffer({...offer,ids:e.target.value})}/></label>:<label>Группа<select aria-label="Группа" value={offer.group_id} onChange={e=>setOffer({...offer,group_id:e.target.value})}><option value="">Выберите</option>{groups.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></label>}<label><input type="checkbox" checked={offer.enabled} onChange={e=>setOffer({...offer,enabled:e.target.checked})}/>Предложение включено</label><button disabled={!offer.create&&!offer.promo_id} onClick={saveOffer}>Сохранить предложение</button></fieldset></section></div></section>;
}
