import React,{useState} from 'react';
type RequestFn=(path:string,options?:RequestInit)=>Promise<any>;
export function TrafficPackages({rows,request,reload}:{rows:any[];request:RequestFn;reload:()=>Promise<void>}){
 const empty={name:'',traffic_gb:50,price:'25.00',plan_id:'',enabled:true,sort_order:0};
 const [form,setForm]=useState<any>(empty),[editing,setEditing]=useState<number|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await request('/api/admin/traffic-packages'+(editing?'/'+editing:''),{method:editing?'PUT':'POST',body:JSON.stringify({...form,plan_id:form.plan_id?Number(form.plan_id):null})});setEditing(null);setForm(empty);await reload()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <div><div className="card"><h2>{editing?'Изменить пакет':'Создать пакет трафика'}</h2><p>Добавляет трафик до конца текущего срока. Для безлимитных подписок покупка недоступна.</p>{error&&<p className="error" role="alert">{error}</p>}<form onSubmit={save}><label>Название<input required maxLength={255} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Трафик, ГБ<input type="number" min={1} max={100000} required value={form.traffic_gb} onChange={e=>setForm({...form,traffic_gb:Number(e.target.value)})}/></label><label>Цена<input type="number" min="0.01" max={1000000} step="0.01" required value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/></label><label>ID тарифа (пусто — все тарифы)<input type="number" min={1} value={form.plan_id} onChange={e=>setForm({...form,plan_id:e.target.value})}/></label><label>Порядок<input type="number" min={-10000} max={10000} value={form.sort_order} onChange={e=>setForm({...form,sort_order:Number(e.target.value)})}/></label><label><input type="checkbox" checked={form.enabled} onChange={e=>setForm({...form,enabled:e.target.checked})}/>Доступен для продажи</label><div className="inline"><button className="primary" disabled={busy}>Сохранить пакет</button>{editing&&<button type="button" disabled={busy} onClick={()=>{setEditing(null);setForm(empty)}}>Отмена</button>}</div></form></div>{rows.map(row=><div className="card" key={row.id}><h3>{row.name} · +{row.traffic_gb} ГБ · {row.price}</h3><p>{row.enabled?'Доступен':'Отключён'} · {row.plan_id?'Тариф №'+row.plan_id:'Все тарифы'}</p><button disabled={busy} onClick={()=>{setEditing(row.id);setForm({...row,plan_id:row.plan_id??''})}}>Изменить</button></div>)}</div>
}
export function SubscriptionOperations({rows,request,reload}:{rows:any[];request:RequestFn;reload:()=>Promise<void>}){
 const [error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function refund(row:any){if(!confirm(`Восстановить условия до заказа №${row.payment_id} и вернуть ${row.amount} ${row.currency} на кошелёк?`))return;setBusy(true);setError('');try{await request(`/api/admin/subscription-operations/${row.id}/refund`,{method:'POST',body:'{}'});await reload()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 const labels:Record<string,string>={queued:'В очереди',applying:'Применяется',applied:'Выполнено',refund_pending:'Возврат требует проверки',refunded:'Возвращено'};
 return <div>{error&&<p className="error" role="alert">{error}</p>}<div className="card"><h2>Смена тарифов и докупка трафика</h2><p>Возврат восстанавливает прежние лимиты перед зачислением в кошелёк. После последующего изменения подписки автоматический возврат заблокирован.</p></div>{!rows.length&&<p>Заказов пока нет.</p>}{rows.map(row=><div className="card" key={row.id}><h3>Заказ №{row.payment_id} · Клиент №{row.user_id}</h3><p>{row.kind==='traffic_addon'?'Докупка трафика':'Смена тарифа'} · {row.amount} {row.currency} · {labels[row.status]||row.status}</p><p>Трафик: {row.before.traffic_gb??'∞'} → {row.after.traffic_gb??'∞'} ГБ · Устройства: {row.before.devices??'∞'} → {row.after.devices??'∞'}</p>{row.error&&<p className="error">{row.error}</p>}{row.status!=='refunded'&&<button disabled={busy} onClick={()=>refund(row)}>Вернуть на кошелёк</button>}</div>)}</div>
}
