import React,{useEffect,useRef,useState} from 'react';
type RequestFn=(path:string,options?:RequestInit)=>Promise<any>;
const localDate=(value:any)=>{const date=new Date(value);return new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16)};
const blank=()=>({title:'',description:'',starts_at:localDate(new Date()),ends_at:localDate(Date.now()+7*86400000),max_responses:1000,reward_amount:'0',require_verified_email:false,require_subscription:false,results_mode:'after_vote',questions:[{text:'',kind:'single',optionsText:'Первый вариант\nВторой вариант'}]});
const labels:Record<string,string>={draft:'Черновик',published:'Опубликован',open:'Доступен',scheduled:'Запланирован',closed:'Завершён'};
export function AdminSurveys({rows:initialRows,request,reload}:{rows:any[];request:RequestFn;reload:()=>Promise<void>}){
 const [rows,setRows]=useState(initialRows),[more,setMore]=useState(initialRows.length===200);
 useEffect(()=>{setRows(initialRows);setMore(initialRows.length===200)},[initialRows]);
 async function older(){setBusy(true);setError('');try{const data=await request('/api/admin/surveys?before='+rows[rows.length-1].id);setRows(prev=>[...prev,...data]);setMore(data.length===200)}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 const [form,setForm]=useState(blank),[editing,setEditing]=useState<number|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[responses,setResponses]=useState<any[]>([]),[responseSurvey,setResponseSurvey]=useState<number|null>(null),[next,setNext]=useState<number|null>(null);
 const locked=useRef(false),responseRequest=useRef(0);
 const set=(key:string,value:any)=>setForm(prev=>({...prev,[key]:value}));
 async function run(path:string,method='POST',body:any={}){if(locked.current)return false;locked.current=true;setBusy(true);setError('');try{await request(path,{method,body:method==='DELETE'?undefined:JSON.stringify(body)});await reload();return true}catch(e:any){setError(e.message);return false}finally{locked.current=false;setBusy(false)}}
 async function save(e:React.FormEvent){e.preventDefault();let data:any;
  try{data={title:form.title,description:form.description,max_responses:form.max_responses,require_verified_email:form.require_verified_email,require_subscription:form.require_subscription,results_mode:form.results_mode,starts_at:new Date(form.starts_at).toISOString(),ends_at:new Date(form.ends_at).toISOString(),reward_amount:form.reward_amount,
   questions:form.questions.map(q=>({text:q.text,kind:q.kind,options:q.kind==='text'?[]:q.optionsText.split('\n').map(x=>x.trim()).filter(Boolean)}))};
   if(!data.title.trim()||data.questions.some((q:any)=>!q.text.trim()||(q.kind!=='text'&&q.options.length<2))){setError('Заполните название, вопросы и минимум два варианта выбора');return;}
  }catch{setError('Укажите корректные даты');return;}
  const ok=await run(editing?`/api/admin/surveys/${editing}`:'/api/admin/surveys',editing?'PUT':'POST',data);if(ok){setEditing(null);setForm(blank())}}
 function edit(row:any){setEditing(row.id);setForm({...row,starts_at:localDate(row.starts_at),ends_at:localDate(row.ends_at),questions:row.questions.map((q:any)=>({...q,optionsText:q.options.join('\n')}))})}
 async function loadResponses(id:number,after=0){const n=++responseRequest.current;setBusy(true);setError('');if(!after){setResponses([]);setNext(null);setResponseSurvey(id)}
  try{const d=await request(`/api/admin/surveys/${id}/responses?after=${after}`);if(n===responseRequest.current){setResponses(prev=>after?[...prev,...d.items]:d.items);setNext(d.next_after)}}catch(e:any){if(n===responseRequest.current)setError(e.message)}finally{if(n===responseRequest.current)setBusy(false)}}
 return <div className="stack">{error&&<p className="error" role="alert">{error}</p>}
 <div className="card"><h2>{editing?'Изменить черновик №'+editing:'Создать опрос'}</h2><p>После публикации условия и варианты фиксируются. Награда — бонус на внутренний баланс, бюджет равен награде × лимиту ответов.</p>
 <form className="form" onSubmit={save}><label>Название<input required maxLength={255} value={form.title} onChange={e=>set('title',e.target.value)}/></label><label>Описание<textarea maxLength={4000} value={form.description} onChange={e=>set('description',e.target.value)}/></label>
 <label>Начало (ваш часовой пояс)<input type="datetime-local" required value={form.starts_at} onChange={e=>set('starts_at',e.target.value)}/></label><label>Окончание (ваш часовой пояс)<input type="datetime-local" required value={form.ends_at} onChange={e=>set('ends_at',e.target.value)}/></label>
 <label>Лимит участников<input type="number" min={1} max={10000} required value={form.max_responses} onChange={e=>set('max_responses',Number(e.target.value))}/></label><label>Награда на баланс<input type="number" min="0" max="10000" step="0.01" required value={form.reward_amount} onChange={e=>{set('reward_amount',e.target.value);if(Number(e.target.value)>0)set('require_verified_email',true)}}/></label>
 <p>Максимальный бюджет: {(Number(form.reward_amount)*Number(form.max_responses)).toFixed(2)}. Валюта фиксируется при создании.</p>
 <label><input type="checkbox" checked={form.require_verified_email} disabled={Number(form.reward_amount)>0} onChange={e=>set('require_verified_email',e.target.checked)}/>Подтверждённый email</label><label><input type="checkbox" checked={form.require_subscription} onChange={e=>set('require_subscription',e.target.checked)}/>Действующая подписка</label>
 <label>Показывать результаты<select value={form.results_mode} onChange={e=>set('results_mode',e.target.value)}><option value="after_vote">После собственного ответа</option><option value="closed">После завершения</option><option value="hidden">Только оператору</option></select></label>
 {form.questions.map((q,i)=><fieldset key={i}><legend>Вопрос {i+1}</legend><label>Текст вопроса<input aria-label={`Вопрос ${i+1}`} required maxLength={1000} value={q.text} onChange={e=>set('questions',form.questions.map((x,j)=>j===i?{...x,text:e.target.value}:x))}/></label>
 <label>Тип ответа<select value={q.kind} onChange={e=>set('questions',form.questions.map((x,j)=>j===i?{...x,kind:e.target.value}:x))}><option value="single">Один вариант</option><option value="multiple">Несколько вариантов</option><option value="text">Свободный текст</option></select></label>
 {q.kind!=='text'&&<label>Варианты, по одному на строке<textarea required value={q.optionsText} onChange={e=>set('questions',form.questions.map((x,j)=>j===i?{...x,optionsText:e.target.value}:x))}/></label>}
 {form.questions.length>1&&<button type="button" onClick={()=>set('questions',form.questions.filter((_,j)=>j!==i))}>Убрать вопрос</button>}</fieldset>)}
 <div className="inline"><button type="button" disabled={busy||form.questions.length>=20} onClick={()=>set('questions',[...form.questions,{text:'',kind:'single',optionsText:'Первый вариант\nВторой вариант'}])}>Добавить вопрос</button><button className="primary" disabled={busy}>Сохранить черновик</button>{editing&&<button type="button" disabled={busy} onClick={()=>{setEditing(null);setForm(blank())}}>Отмена изменения</button>}</div>
 </form></div>
 {!rows.length&&<p>Опросов пока нет.</p>}{rows.map(row=><article className="card" key={row.id}><h3>#{row.id} · {row.title}</h3><p>{labels[row.phase]||row.phase} · ответов {row.response_count}/{row.max_responses} · награда {row.reward_amount} {row.currency}</p><p>Бюджет: {row.budget_credited}/{row.budget_limit} {row.currency} · до {new Date(row.ends_at).toLocaleString()}</p>
 <div className="inline">{row.state==='draft'&&<><button disabled={busy} onClick={()=>edit(row)}>Изменить</button><button disabled={busy} onClick={()=>confirm(`Опубликовать неизменяемые условия и бюджет ${row.budget_limit} ${row.currency}?`)&&run(`/api/admin/surveys/${row.id}/publish`)}>Опубликовать</button><button disabled={busy} onClick={()=>confirm('Удалить черновик?')&&run(`/api/admin/surveys/${row.id}`,'DELETE')}>Удалить</button></>}
 {row.state==='published'&&<button disabled={busy} onClick={()=>confirm('Закрыть участие? Повторное открытие не предусмотрено.')&&run(`/api/admin/surveys/${row.id}/close`)}>Закрыть опрос</button>}<button disabled={busy} onClick={()=>loadResponses(row.id)}>Ответы участников</button></div>
 {row.questions.map((q:any,i:number)=><div key={i}><strong>{q.text}</strong>{q.kind==='text'?<p>Текстовых ответов: {row.statistics?.[i]?.answered||0}</p>:q.options.map((option:string,j:number)=><p key={j}>{option}: {row.statistics?.[i]?.[j]||0}</p>)}</div>)}</article>)}
 {more&&<button disabled={busy} onClick={older}>Предыдущие опросы</button>}
 {responseSurvey!=null&&<div className="card"><h3>Ответы опроса №{responseSurvey}</h3><p>Свободный текст может содержать личные данные. Экспорт или публикация требует отдельной проверки.</p>{!responses.length&&!busy&&<p>Ответов пока нет.</p>}{responses.map(r=><article key={r.id}><h4>Ответ №{r.id} · {r.user_id==null?'Аккаунт обезличен':'Клиент №'+r.user_id}</h4>{r.answers.map((a:any,i:number)=><p key={i} style={{whiteSpace:'pre-wrap'}}>{i+1}. {a.text||a.choices.map((x:number)=>rows.find(s=>s.id===responseSurvey)?.questions[i]?.options[x]||String(x)).join(', ')}</p>)}<p>Награда {r.reward_amount} {r.currency}</p></article>)}{next!=null&&<button disabled={busy} onClick={()=>loadResponses(responseSurvey,next)}>Ещё ответы</button>}</div>}
 </div>
}
