from alembic import op
import sqlalchemy as sa
revision="0001";down_revision=None;branch_labels=None;depends_on=None
def upgrade():
 op.create_table("operators",sa.Column("id",sa.Integer,primary_key=True),sa.Column("login",sa.String(120),unique=True,nullable=False),sa.Column("password_hash",sa.String(255),nullable=False),sa.Column("role",sa.String(30),nullable=False),sa.Column("active",sa.Boolean,nullable=False,server_default=sa.true()),sa.Column("totp_secret",sa.String(64)),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now()))
 op.create_table("categories",sa.Column("id",sa.Integer,primary_key=True),sa.Column("name",sa.String(120),unique=True,nullable=False))
 op.create_table("macros",sa.Column("id",sa.Integer,primary_key=True),sa.Column("title",sa.String(160),nullable=False),sa.Column("body",sa.Text,nullable=False),sa.Column("active",sa.Boolean,nullable=False,server_default=sa.true()))
 op.create_table("tickets",sa.Column("id",sa.Integer,primary_key=True),sa.Column("telegram_user_id",sa.BigInteger,index=True,nullable=False),sa.Column("username",sa.String(255),server_default=""),sa.Column("full_name",sa.String(255),server_default=""),sa.Column("subject",sa.String(255),server_default=""),sa.Column("status",sa.String(30),server_default="new",index=True),sa.Column("priority",sa.String(30),server_default="normal"),sa.Column("category_id",sa.Integer,sa.ForeignKey("categories.id")),sa.Column("assigned_to",sa.Integer,sa.ForeignKey("operators.id")),sa.Column("sla_deadline",sa.DateTime(timezone=True)),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now()),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now()))
 op.create_table("messages",sa.Column("id",sa.Integer,primary_key=True),sa.Column("ticket_id",sa.Integer,sa.ForeignKey("tickets.id"),index=True,nullable=False),sa.Column("sender",sa.String(30),nullable=False),sa.Column("text",sa.Text,server_default=""),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now()))
 op.create_table("attachments",sa.Column("id",sa.Integer,primary_key=True),sa.Column("ticket_id",sa.Integer,sa.ForeignKey("tickets.id"),index=True,nullable=False),sa.Column("message_id",sa.Integer,sa.ForeignKey("messages.id")),sa.Column("filename",sa.String(255),nullable=False),sa.Column("path",sa.String(1000),nullable=False),sa.Column("content_type",sa.String(255),server_default="application/octet-stream"),sa.Column("size",sa.Integer,server_default="0"),sa.Column("telegram_file_id",sa.String(255)))
 op.create_table("audit_logs",sa.Column("id",sa.Integer,primary_key=True),sa.Column("operator_id",sa.Integer,sa.ForeignKey("operators.id")),sa.Column("action",sa.String(255),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now()))
def downgrade():
 for x in ["audit_logs","attachments","messages","tickets","macros","categories","operators"]:op.drop_table(x)
