"""Knowledge, automation, omnichannel identities, callbacks and holidays."""
from alembic import op
import sqlalchemy as sa
revision='0003'; down_revision='0002'; branch_labels=None; depends_on=None

def upgrade():
    op.create_table('knowledge_articles', sa.Column('id',sa.Integer,primary_key=True),sa.Column('title',sa.String(220),nullable=False),sa.Column('slug',sa.String(240),unique=True,nullable=False),sa.Column('body',sa.Text,nullable=False),sa.Column('category_id',sa.Integer,sa.ForeignKey('categories.id')),sa.Column('status',sa.String(20),nullable=False,server_default='draft'),sa.Column('visibility',sa.String(20),nullable=False,server_default='internal'),sa.Column('views',sa.Integer,nullable=False,server_default='0'),sa.Column('helpful_yes',sa.Integer,nullable=False,server_default='0'),sa.Column('helpful_no',sa.Integer,nullable=False,server_default='0'),sa.Column('updated_by',sa.Integer,sa.ForeignKey('operators.id')),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now()),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.func.now()))
    op.create_table('holidays',sa.Column('id',sa.Integer,primary_key=True),sa.Column('day',sa.DateTime(timezone=True),unique=True,nullable=False),sa.Column('title',sa.String(160),nullable=False),sa.Column('is_working',sa.Boolean,nullable=False,server_default=sa.false()))
    op.create_table('automation_rules',sa.Column('id',sa.Integer,primary_key=True),sa.Column('title',sa.String(160),nullable=False),sa.Column('enabled',sa.Boolean,nullable=False,server_default=sa.true()),sa.Column('event',sa.String(50),nullable=False),sa.Column('conditions',sa.JSON,nullable=False),sa.Column('actions',sa.JSON,nullable=False),sa.Column('last_error',sa.Text,nullable=False,server_default=''),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.func.now()))
    op.create_table('webhook_endpoints',sa.Column('id',sa.Integer,primary_key=True),sa.Column('name',sa.String(160),nullable=False),sa.Column('url',sa.String(1000),nullable=False),sa.Column('secret',sa.String(255),nullable=False),sa.Column('events',sa.JSON,nullable=False),sa.Column('enabled',sa.Boolean,nullable=False,server_default=sa.true()),sa.Column('last_status',sa.Integer),sa.Column('last_error',sa.Text,nullable=False,server_default=''),sa.Column('last_sent_at',sa.DateTime(timezone=True)))
    op.create_table('call_requests',sa.Column('id',sa.Integer,primary_key=True),sa.Column('ticket_id',sa.Integer,sa.ForeignKey('tickets.id'),nullable=False),sa.Column('telegram_user_id',sa.BigInteger,nullable=False),sa.Column('phone',sa.String(64),nullable=False,server_default=''),sa.Column('preferred_at',sa.DateTime(timezone=True)),sa.Column('status',sa.String(30),nullable=False,server_default='queued'),sa.Column('assigned_to',sa.Integer,sa.ForeignKey('operators.id')),sa.Column('notes',sa.Text,nullable=False,server_default=''),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now()),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.func.now()))
    op.create_index('ix_call_requests_ticket_id','call_requests',['ticket_id']); op.create_index('ix_call_requests_status','call_requests',['status'])
    op.create_table('channel_identities',sa.Column('id',sa.Integer,primary_key=True),sa.Column('client_id',sa.BigInteger,nullable=False),sa.Column('channel',sa.String(30),nullable=False),sa.Column('external_id',sa.String(255),nullable=False),sa.Column('address',sa.String(255),nullable=False,server_default=''),sa.Column('verified',sa.Boolean,nullable=False,server_default=sa.false()),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now()))
    op.create_index('ix_channel_identities_client_id','channel_identities',['client_id'])

def downgrade():
    for x in ['channel_identities','call_requests','webhook_endpoints','automation_rules','holidays','knowledge_articles']: op.drop_table(x)
