"""v20 full payment platform."""
from alembic import op
import sqlalchemy as sa
revision="0040_v20_payment_platform"
down_revision="0039_v19_marketplace"
branch_labels=None
depends_on=None

def upgrade():
    op.create_table("payment_tax_profiles",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("user_id",sa.Integer(),nullable=False),sa.Column("country",sa.String(2),nullable=False,server_default="DE"),sa.Column("vat_id",sa.String(64)),sa.Column("business_name",sa.String(255)),sa.Column("tax_exempt",sa.Boolean(),nullable=False,server_default=sa.false()),sa.Column("reverse_charge",sa.Boolean(),nullable=False,server_default=sa.false()),sa.Column("created_at",sa.DateTime(),nullable=False),sa.Column("updated_at",sa.DateTime(),nullable=False))
    op.create_index("ix_payment_tax_profiles_user_id","payment_tax_profiles",["user_id"],unique=True)
    op.create_table("payment_invoices",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("payment_id",sa.Integer(),nullable=False),sa.Column("invoice_number",sa.String(64),nullable=False),sa.Column("subtotal",sa.Numeric(12,2),nullable=False),sa.Column("tax_amount",sa.Numeric(12,2),nullable=False,server_default="0"),sa.Column("total",sa.Numeric(12,2),nullable=False),sa.Column("tax_rate",sa.Numeric(6,3),nullable=False,server_default="0"),sa.Column("currency",sa.String(3),nullable=False),sa.Column("country",sa.String(2),nullable=False),sa.Column("status",sa.String(24),nullable=False,server_default="issued"),sa.Column("issued_at",sa.DateTime(),nullable=False))
    op.create_index("ix_payment_invoices_payment_id","payment_invoices",["payment_id"],unique=True); op.create_index("ix_payment_invoices_invoice_number","payment_invoices",["invoice_number"],unique=True)
    op.create_table("payment_chargebacks",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("payment_id",sa.Integer(),nullable=False),sa.Column("provider",sa.String(32),nullable=False),sa.Column("external_id",sa.String(255),nullable=False),sa.Column("amount",sa.Numeric(12,2),nullable=False),sa.Column("currency",sa.String(3),nullable=False),sa.Column("status",sa.String(32),nullable=False,server_default="open"),sa.Column("reason",sa.Text()),sa.Column("evidence",sa.JSON()),sa.Column("created_at",sa.DateTime(),nullable=False),sa.Column("updated_at",sa.DateTime(),nullable=False))
    op.create_index("ix_payment_chargebacks_external_id","payment_chargebacks",["external_id"],unique=True); op.create_index("ix_payment_chargebacks_payment_id","payment_chargebacks",["payment_id"])
    op.create_table("payment_risk_assessments",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("payment_id",sa.Integer(),nullable=False),sa.Column("score",sa.Integer(),nullable=False,server_default="0"),sa.Column("decision",sa.String(24),nullable=False,server_default="allow"),sa.Column("signals",sa.JSON()),sa.Column("created_at",sa.DateTime(),nullable=False)); op.create_index("ix_payment_risk_assessments_payment_id","payment_risk_assessments",["payment_id"],unique=True)
    op.create_table("payment_provider_metrics",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("provider",sa.String(32),nullable=False),sa.Column("day",sa.String(10),nullable=False),sa.Column("attempts",sa.Integer(),nullable=False,server_default="0"),sa.Column("succeeded",sa.Integer(),nullable=False,server_default="0"),sa.Column("failed",sa.Integer(),nullable=False,server_default="0"),sa.Column("refunded",sa.Integer(),nullable=False,server_default="0"),sa.Column("gross_amount",sa.Numeric(14,2),nullable=False,server_default="0"),sa.Column("fees_amount",sa.Numeric(14,2),nullable=False,server_default="0"),sa.Column("net_amount",sa.Numeric(14,2),nullable=False,server_default="0")); op.create_index("ix_payment_provider_metrics_provider","payment_provider_metrics",["provider"]); op.create_index("ix_payment_provider_metrics_day","payment_provider_metrics",["day"])
    op.create_table("gift_cards",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("code_hash",sa.String(128),nullable=False),sa.Column("code_prefix",sa.String(16),nullable=False),sa.Column("value",sa.Numeric(12,2),nullable=False),sa.Column("currency",sa.String(3),nullable=False,server_default="EUR"),sa.Column("balance",sa.Numeric(12,2),nullable=False),sa.Column("expires_at",sa.DateTime()),sa.Column("enabled",sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column("created_at",sa.DateTime(),nullable=False)); op.create_index("ix_gift_cards_code_hash","gift_cards",["code_hash"],unique=True); op.create_index("ix_gift_cards_code_prefix","gift_cards",["code_prefix"])
    op.create_table("corporate_accounts",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("owner_user_id",sa.Integer(),nullable=False),sa.Column("name",sa.String(255),nullable=False),sa.Column("vat_id",sa.String(64)),sa.Column("country",sa.String(2),nullable=False,server_default="DE"),sa.Column("payment_terms_days",sa.Integer(),nullable=False,server_default="14"),sa.Column("credit_limit",sa.Numeric(14,2),nullable=False,server_default="0"),sa.Column("enabled",sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column("created_at",sa.DateTime(),nullable=False)); op.create_index("ix_corporate_accounts_owner_user_id","corporate_accounts",["owner_user_id"])
    op.create_table("payment_price_experiments",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("key",sa.String(64),nullable=False),sa.Column("rules",sa.JSON()),sa.Column("enabled",sa.Boolean(),nullable=False,server_default=sa.false()),sa.Column("created_at",sa.DateTime(),nullable=False)); op.create_index("ix_payment_price_experiments_key","payment_price_experiments",["key"],unique=True)

def downgrade():
    for t in ["payment_price_experiments","corporate_accounts","gift_cards","payment_provider_metrics","payment_risk_assessments","payment_chargebacks","payment_invoices","payment_tax_profiles"]: op.drop_table(t)
