import React,{useEffect,useState} from 'react';
export type PageBlock={kind:'hero'|'text'|'cta'|'features'|'faq';title:string;text:string;label:string;url:string;items:{title:string;text:string}[]};
export function ContentBlocks({blocks}:{blocks:PageBlock[]}){
 return <>{blocks.map((b,i)=><section className="form-card" key={i}>{b.title&&<h2>{b.title}</h2>}{b.text&&<p style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{b.text}</p>}{b.kind==='cta'&&<a className="btn primary" href={b.url} rel="noopener noreferrer">{b.label}</a>}{b.kind==='features'&&<ul>{b.items.map((x,j)=><li key={j}><strong>{x.title}</strong><p style={{whiteSpace:'pre-wrap'}}>{x.text}</p></li>)}</ul>}{b.kind==='faq'&&b.items.map((x,j)=><details key={j}><summary>{x.title}</summary><p style={{whiteSpace:'pre-wrap'}}>{x.text}</p></details>)}</section>)}</>;
}
type Requester=(path:string,options?:RequestInit)=>Promise<any>;
export function PublicPages({request,route,locale}:{request:Requester;route:string;locale:string}){
 const[rows,setRows]=useState<any[]>([]),[page,setPage]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[kind,setKind]=useState(''),[offset,setOffset]=useState(0),[more,setMore]=useState(false);
 const slug=route.startsWith('page/')?route.slice(5):'';
 useEffect(()=>{let live=true;setBusy(true);setError('');setPage(null);setRows([]);setOffset(0);request(slug?`/api/public/pages/${encodeURIComponent(slug)}?locale=${locale}`:`/api/public/pages?locale=${locale}${kind?`&kind=${kind}`:''}`).then(x=>{if(!live)return;if(slug)setPage(x);else{setRows(x);setOffset(x.length);setMore(x.length===50)}}).catch(x=>{if(live)setError(x.message)}).finally(()=>{if(live)setBusy(false)});return()=>{live=false}},[request,slug,locale,kind]);
 async function next(){setBusy(true);setError('');try{const x=await request(`/api/public/pages?locale=${locale}&offset=${offset}${kind?`&kind=${kind}`:''}`);setRows(r=>[...r,...x]);setOffset(n=>n+x.length);setMore(x.length===50)}catch(x:any){setError(x.message)}finally{setBusy(false)}}
 return <main className="content-wrap"><div className="btn-row"><a href="#overview">{locale==='ru'?'В магазин':'Shop'}</a>{slug&&<a href="#pages">{locale==='ru'?'Все публикации':'All publications'}</a>}</div>{error&&<p role="alert" className="error">{error}</p>}{busy&&<p>{locale==='ru'?'Загрузка…':'Loading…'}</p>}{page&&<article><h1>{page.title}</h1><p>{page.summary}</p><ContentBlocks blocks={page.blocks}/><small>{locale==='ru'?'Версия публикации':'Published revision'}: {page.revision}</small></article>}{!slug&&<><h1>{locale==='ru'?'Новости и документы':'News and documents'}</h1><label>{locale==='ru'?'Тип публикации':'Publication type'}<select aria-label="Тип публикации" value={kind} onChange={e=>setKind(e.target.value)}><option value="">Все / All</option><option value="news">Новости / News</option><option value="landing">Лендинги / Landing pages</option><option value="legal">Юридические страницы / Legal pages</option></select></label>{rows.map(x=><article className="form-card" key={x.slug}><h2><a href={`#page/${x.slug}`}>{x.title}</a></h2><p>{x.summary}</p></article>)}{!busy&&!rows.length&&!error&&<p>{locale==='ru'?'Публикаций пока нет':'No publications yet'}</p>}{more&&<button disabled={busy} onClick={next}>{locale==='ru'?'Показать ещё':'Load more'}</button>}</>}</main>;
}
