import React,{useEffect,useRef,useState} from 'react';
type RequestFn=(path:string,options?:RequestInit)=>Promise<any>;
const stateLabel=(state:any)=>`${state.traffic_gb==null?'Безлимитный трафик':state.traffic_gb+' ГБ'} · ${state.devices==null?'Без лимита устройств':state.devices+' устройств'}`;
const statuses:Record<string,string>={queued:'Ожидает обработки',applying:'Применяется',applied:'Выполнено',refund_pending:'Возврат проверяется',refunded:'Возвращено'};
export function SubscriptionCommerce({request,reload}:{request:RequestFn;reload:()=>Promise<void>}){
 const [catalog,setCatalog]=useState<any>(null),[history,setHistory]=useState<any[]>([]),[choice,setChoice]=useState(''),[quote,setQuote]=useState<any>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const mounted=useRef(true),locked=useRef(false),keys=useRef<Record<string,string>>({});
 async function load(){try{const [c,h]=await Promise.all([request('/api/me/subscription/commerce'),request('/api/me/subscription/operations')]);if(mounted.current){setCatalog(c);setHistory(h)}}catch(e:any){if(mounted.current)setError(e.message)}}
 useEffect(()=>{mounted.current=true;load();return()=>{mounted.current=false}},[]);
 async function calculate(){if(locked.current)return;locked.current=true;setBusy(true);setError('');setNotice('');setQuote(null);try{const [kind,id]=choice.split(':');const q=await request('/api/me/subscription/quote',{method:'POST',body:JSON.stringify({kind,subscription_id:catalog.subscription_id,...(kind==='traffic_addon'?{package_id:Number(id)}:{plan_id:Number(id)})})});if(mounted.current)setQuote(q)}catch(e:any){if(mounted.current)setError(e.message)}finally{locked.current=false;if(mounted.current)setBusy(false)}}
 async function purchase(){if(locked.current||!quote)return;locked.current=true;setBusy(true);setError('');const id=quote.id;keys.current[id]??=crypto.randomUUID();try{await request('/api/me/subscription/purchase',{method:'POST',body:JSON.stringify({quote_id:id}),headers:{'Idempotency-Key':keys.current[id]}});if(mounted.current){setQuote(null);setNotice('Заказ принят. Его статус показан ниже.');await reload();await load()}}catch(e:any){if(mounted.current)setError(e.message)}finally{locked.current=false;if(mounted.current)setBusy(false)}}
 return <section className="workspace-history"><h3>Смена тарифа и дополнительный трафик</h3><p className="section-sub">Оплата с кошелька. Срок подписки сохраняется. При смене тарифа оплачивается разница за оставшиеся дни; снижение стоимости не зачисляет деньги на баланс.</p>{error&&<p className="workspace-alert error" role="alert">{error}</p>}{notice&&<p className="workspace-alert" role="status">{notice}</p>}{catalog&&<><p>Баланс: {catalog.balance} {catalog.currency} · {stateLabel(catalog.current)}</p><form className="workspace-form" onSubmit={e=>{e.preventDefault();calculate()}}><label className="field">Новые условия<select required value={choice} disabled={busy} onChange={e=>{setChoice(e.target.value);setQuote(null)}}><option value="">Выберите изменение</option>{catalog.plans.map((p:any)=><option key={`p${p.id}`} value={`subscription_change:${p.id}`}>{p.name} · {p.price} {catalog.currency} / {p.duration_days} дней</option>)}{catalog.current.traffic_gb!=null&&catalog.packages.map((p:any)=><option key={`t${p.id}`} value={`traffic_addon:${p.id}`}>+{p.traffic_gb} ГБ · {p.price} {catalog.currency}</option>)}</select></label><button className="btn-ghost" disabled={busy||!choice}>Рассчитать доплату</button></form>{quote&&<article className="workspace-record"><div><strong>К оплате: {quote.amount} {quote.currency}</strong><p>{stateLabel(quote.before)} → {stateLabel(quote.after)}</p><p>Действует до {new Date(quote.after.expires_at).toLocaleString()}</p><small>Расчёт действителен до {new Date(quote.expires_at).toLocaleTimeString()}. При потере ответа повторите этот заказ.</small><div className="btn-row"><button className="btn-primary" disabled={busy||Number(quote.amount)>Number(catalog.balance)} onClick={purchase}>Подтвердить с кошелька</button></div>{Number(quote.amount)>Number(catalog.balance)&&<p>Сначала пополните кошелёк.</p>}</div></article>}</>}<button className="btn-ghost" disabled={busy} onClick={load}>Обновить статус заказов</button>{history.map(op=><article className="workspace-record" key={op.id}><div><strong>Заказ №{op.payment_id} · {op.amount} {op.currency}</strong><p>{statuses[op.status]||op.status} · {op.fulfillment_status==='failed'?'Повтор обработки ожидается':new Date(op.created_at).toLocaleString()}</p><p>{stateLabel(op.after)}</p></div></article>)}</section>
}
