import React, {useEffect, useRef, useState} from "react";
import {SubscriptionCommerce} from "./subscription-commerce";
import {ReferralNetwork} from "./referral-network";
import {SupportConversation} from "./support-conversation";

type RequestFn = (path: string, options?: RequestInit) => Promise<any>;
type Props = {key?:string;kind: string; request: RequestFn; reload: () => Promise<void>; plans: any[]; provider: string; providers: string[]; currency: string; api: string; botUsername?:string};
const LABELS: Record<string,string> = {pending:"Ожидает оплаты",creating:"Создаётся",creation_unknown:"Требует сверки",paid:"Оплачен",fulfilled:"Доступ выдан",failed:"Ошибка",completed:"Завершено",processing:"Обрабатывается",queued:"В очереди",refunded:"Возвращён",active:"Активна",cancel_scheduled:"Отмена запланирована",expired:"Истекла",ready:"Готов к передаче",used:"Активирован",requested:"Запрошено",approved:"Одобрено",rejected:"Отклонено",disabled:"Отключено",open:"Открыто",closed:"Закрыто",resolved:"Решено",survey_reward:"Награда за опрос",wallet_import:"Перенос начального баланса",wallet_topup:"Пополнение",wallet_spend:"Покупка подписки",gift_purchase:"Покупка подарка",wallet_topup_refund:"Возврат пополнения",gift_card:"Подарочная карта",wallet_purchase_refund:"Возврат покупки"};
const label = (v:string) => /^reward_level_[2-5]$/.test(v)?`Награда, уровень ${v.slice(-1)}`:/^refund_level_[2-5]$/.test(v)?`Отмена награды, уровень ${v.slice(-1)}`:v==="reward"?"Реферальная награда":v.startsWith("refund_reversal:")?"Отмена реферальной награды":LABELS[v] || v || "—";
const date = (v:string) => v ? new Date(v).toLocaleString() : "—";
const AGENTS:Record<string,string>={yookassa:"YooKassa",rollypay:"RollyPay",platega:"Platega",sandbox:"Тестовый платёж"};
const PATHS:Record<string,string[]>={wallet:["/api/me/wallet/history"],payments:["/api/me/billing-center"],subscription:["/api/me/billing-center","/api/me/auto-renew"],gifts:["/api/me/gifts"],referral:["/api/me/referral","/api/me/referral/ledger","/api/me/referral/withdrawals","/api/me/referral/network"],security:["/api/me/security-center"],notifications:["/api/me/notifications"],support:["/api/me/support/tickets"]};

export function Workspace({kind,request,reload,plans,provider,providers,currency,api,botUsername}:Props) {
 const [data,setData]=useState<any[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
 const [amount,setAmount]=useState("500"),[agent,setAgent]=useState(provider),[code,setCode]=useState(""),[plan,setPlan]=useState(""),[destination,setDestination]=useState(""),[subject,setSubject]=useState(""),[message,setMessage]=useState("");
 const [giftNew,setGiftNew]=useState(false);
 const [supportTicket,setSupportTicket]=useState<number|null>(null);
 const serial=useRef(0), locked=useRef(false), keys=useRef<Record<string,string>>({});
 useEffect(()=>{setAgent(providers.includes(provider)?provider:providers[0]||"")},[provider,providers.join(",")]);
 async function load(){const n=++serial.current;setLoading(true);setError("");try{const values=await Promise.all((PATHS[kind]||[]).map(p=>request(p)));if(n===serial.current)setData(values)}catch(e:any){if(n===serial.current)setError(e.message)}finally{if(n===serial.current)setLoading(false)}}
 useEffect(()=>{load();return()=>{serial.current++}},[kind]);
 async function run(path:string,body:any={},method="POST",idempotent=false){
  if(locked.current)return;locked.current=true;setBusy(true);setError("");setNotice("");
  const fingerprint=path+JSON.stringify(body);if(idempotent&&!keys.current[fingerprint])keys.current[fingerprint]=crypto.randomUUID();
  try{const result=await request(path,{method,body:method==="DELETE"?undefined:JSON.stringify(body),headers:idempotent?{"Idempotency-Key":keys.current[fingerprint]}:{}});
   delete keys.current[fingerprint];
   if(path==="/api/me/security/revoke-all"){location.reload();return true}
   if(result.url){const url=new URL(result.url,location.origin);if(url.protocol!=="https:"&&url.origin!==location.origin)throw Error("Некорректная ссылка оплаты");location.assign(url.href);return}
   setNotice(result.code?`Подарок создан. Код: ${result.code}`:result.already_redeemed?"Этот подарок уже активирован вашим аккаунтом":"Изменения сохранены");setCode("");await reload();await load();return true;
  }catch(e:any){setError(e.message)}finally{locked.current=false;setBusy(false)}
 }
 async function copy(value:string){try{await navigator.clipboard.writeText(value);setNotice("Скопировано")}catch{setError("Не удалось скопировать. Выделите текст и скопируйте вручную.")}}
 const payments=data[0]?.payments||[],sub=data[0]?.subscription,renew=data[1]||{},ref=data[0]||{};
 const paymentChoice=<label className="field">Способ оплаты<select value={agent} onChange={e=>setAgent(e.target.value)}>{providers.map(p=><option key={p} value={p}>{AGENTS[p]||p}</option>)}</select>{!providers.length&&<small>Платёжные агенты временно недоступны</small>}</label>;
 return <div className="workspace-section">
  {error&&<div className="workspace-alert error" role="alert">{error}<button className="btn-ghost" onClick={load}>Обновить данные</button></div>}{notice&&<div className="workspace-alert" role="status">{notice}</div>}
  {loading?<p role="status">Загрузка…</p>:<>
   {kind==="wallet"&&<><div className="workspace-balance"><span>Баланс кошелька</span><strong>{data[0]?.balance||"0.00"} {currency}</strong><p>Пополните баланс для покупки подписки или подарка.</p></div><form className="workspace-form" onSubmit={e=>{e.preventDefault();run("/api/me/wallet/topup",{amount:Number(amount),provider:agent},"POST",true)}}><label className="field">Сумма пополнения<input type="number" min="50" max="100000" step="0.01" required value={amount} onChange={e=>setAmount(e.target.value)}/></label>{paymentChoice}<button className="btn-primary" disabled={busy||!agent}>Пополнить</button></form><h3>Активировать подарочную карту</h3><form className="workspace-form" onSubmit={e=>{e.preventDefault();run("/api/me/payment/gift-card/redeem",{code:code.trim()})}}><label className="field">Код карты<input value={code} onChange={e=>setCode(e.target.value)} required maxLength={128}/></label><button className="btn-primary" disabled={busy}>Зачислить на баланс</button></form><History title="Операции кошелька" rows={data[0]?.items} columns={[["created_at","Дата"],["kind","Операция"],["direction","Направление"],["amount","Сумма"],["currency","Валюта"]]}/></>}
   {kind==="payments"&&<><p className="section-sub">Оплата и выдача VPN показаны отдельно. Подтверждённый платёж может ожидать обработки.</p><History title="История платежей" rows={payments} columns={[["id","№"],["created_at","Дата"],["amount","Сумма"],["currency","Валюта"],["status","Оплата"],["fulfillment_status","Доступ"]]}/>{payments.filter((p:any)=>["paid","fulfilled","refunded"].includes(p.status)).map((p:any)=><a className="btn-ghost" key={p.id} href={`${api}/api/me/payments/${p.id}/invoice`}>Квитанция №{p.id} · PDF</a>)}</>}
   {kind==="subscription"&&<><div className="workspace-balance"><span>Ваша подписка</span><strong>{label(sub?.status)}</strong><p>Действует до {date(sub?.expires_at)}</p>{sub?.scheduled_cancel_at&&<p>Отмена запланирована на {date(sub.scheduled_cancel_at)}</p>}</div>{sub?<div className="btn-row"><button className="btn-ghost" disabled={busy} onClick={()=>{const action=sub.status==="cancel_scheduled"?"resume":"cancel";if(action==="resume"||confirm("Отменить подписку после окончания оплаченного срока?"))run("/api/me/subscription/lifecycle",{action})}}>{sub.status==="cancel_scheduled"?"Возобновить подписку":"Отменить после окончания"}</button></div>:<p>Выберите тариф, чтобы подключить VPN.</p>}<h3>Автопродление</h3>{renew.renewal_terms&&<p>Следующее продление: {renew.renewal_terms.amount} {renew.renewal_terms.currency}, {renew.renewal_terms.days} дней · {renew.renewal_terms.traffic_gb==null?"Безлимитный трафик":`${renew.renewal_terms.traffic_gb} ГБ`} · {renew.renewal_terms.devices==null?"Устройства без ограничения":`${renew.renewal_terms.devices} устройств`}</p>}<p>{renew.enabled?"Включено":"Выключено"} · сохранённый способ {renew.configured?"подключён":"отсутствует"}</p><p className="section-sub">Автопродление доступно через YooKassa после сохранения способа оплаты.</p><div className="btn-row"><button className="btn-primary" disabled={busy||(!renew.enabled&&!renew.configured)} onClick={()=>run("/api/me/auto-renew",{enabled:!renew.enabled},"PUT")}>{renew.enabled?"Отключить автопродление":"Включить автопродление"}</button>{renew.configured&&<button className="btn-ghost" disabled={busy} onClick={()=>confirm("Удалить сохранённый способ оплаты?")&&run("/api/me/auto-renew/method",{},"DELETE")}>Удалить способ оплаты</button>}</div>{renew.last_error&&<p className="error">{renew.last_error}</p>}{sub&&["active","cancel_scheduled"].includes(sub.status)&&<SubscriptionCommerce request={request} reload={reload}/>}</>}
   {kind==="gifts"&&<><h3>Активировать подарок</h3><form className="workspace-form" onSubmit={e=>{e.preventDefault();run("/api/me/gifts/redeem",{code:code.trim(),new_subscription:giftNew})}}><label className="field">Подарочный код<input value={code} onChange={e=>setCode(e.target.value)} required maxLength={64} placeholder="GIFT_…"/></label><label><input type="checkbox" checked={giftNew} onChange={e=>setGiftNew(e.target.checked)}/> Создать отдельную подписку для подарка</label><button className="btn-primary" disabled={busy}>Активировать</button></form><h3>Подарить подписку</h3><p className="section-sub">Стоимость списывается с кошелька. Покупатель не может активировать свой подарок.</p><form className="workspace-form" onSubmit={e=>{e.preventDefault();run("/api/me/gifts/purchase",{plan_id:Number(plan)},"POST",true)}}><label className="field">Тариф<select value={plan} onChange={e=>setPlan(e.target.value)} required><option value="">Выберите тариф</option>{plans.map(p=><option key={p.id} value={p.id}>{p.name} · {p.price} {currency}</option>)}</select></label><button className="btn-primary" disabled={busy||!plan}>Купить в подарок</button></form><h3>Мои подарки</h3>{!(data[0]||[]).length&&<p className="section-sub">Вы ещё не покупали подарки.</p>}{(data[0]||[]).map((gift:any)=><article className="workspace-record" key={gift.id}><div><strong>{gift.plan}</strong><p>{label(gift.status)} · {date(gift.created_at)}</p>{gift.code&&<code>{gift.code}</code>}</div>{gift.code&&<button className="btn-ghost" onClick={()=>copy(gift.code)}>Скопировать код</button>}</article>)}</>}
   {kind==="referral"&&<><div className="metrics"><div className="metric"><span className="label">Приглашения с оплатой</span><strong className="value">{ref.referred_count||0}</strong></div><div className="metric"><span className="label">Начислено</span><strong className="value">{ref.reward_total||0} {currency}</strong></div><div className="metric"><span className="label">Доступно к выводу</span><strong className="value">{ref.balance||0} {currency}</strong></div></div><h3>Ваш код приглашения</h3><div className="btn-row"><code>{ref.code||"—"}</code><button className="btn-ghost" disabled={!ref.code} onClick={()=>copy(ref.code)}>Скопировать</button></div>{botUsername&&<div className="btn-row"><button className="btn-primary" disabled={!ref.code} onClick={()=>copy(`https://t.me/${botUsername}?start=ref_${ref.code}`)}>Скопировать ссылку приглашения</button></div>}<p>Вознаграждение по уровням: {(ref.level_percentages||[ref.reward_percent||0]).join("% / ")}%</p><ReferralNetwork data={data[3]}/><h3>Запросить выплату</h3><form className="workspace-form" onSubmit={e=>{e.preventDefault();run("/api/me/referral/withdrawals",{amount:Number(amount),destination},"POST",true)}}><label className="field">Сумма<input type="number" min="1" max={ref.balance||0} step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} required/></label><label className="field">Реквизиты<input value={destination} onChange={e=>setDestination(e.target.value)} required maxLength={255}/></label><button className="btn-primary" disabled={busy||Number(amount)>Number(ref.balance||0)}>Запросить</button></form><History title="Мои выплаты" rows={data[2]} columns={[["id","№"],["amount","Сумма"],["status","Статус"],["created_at","Дата"]]}/><History title="Начисления" rows={data[1]} columns={[["created_at","Дата"],["amount","Сумма"],["kind","Операция"]]}/></>}
   {kind==="security"&&<><h3>Активные сессии</h3><p className="section-sub">После отзыва всех сессий потребуется снова войти в кабинет и приложения.</p><button className="btn-ghost" disabled={busy} onClick={async()=>{if(!confirm("Выйти из всех сессий и приложений?"))return;await run("/api/me/security/revoke-all")}}>Выйти на всех устройствах</button><History title="История входов" rows={data[0]?.sessions} columns={[["ip","IP"],["created_at","Вход"],["last_seen_at","Активность"],["revoked_at","Отозвана"]]}/><History title="События безопасности" rows={data[0]?.events} columns={[["action","Событие"],["created_at","Дата"]]}/></>}
   {kind==="notifications"&&<><h3>Уведомления</h3>{!(data[0]||[]).length&&<p>Уведомлений пока нет.</p>}{(data[0]||[]).map((n:any)=><article className={`workspace-record ${n.read?"":"unread"}`} key={n.id}><div><strong>{n.title}</strong><p>{n.body}</p><small>{date(n.created_at)}</small></div>{!n.read&&<button className="btn-ghost" disabled={busy} onClick={()=>run(`/api/me/notifications/${n.id}/read`)}>Прочитано</button>}</article>)}</>}
   {kind==="support"&&<><h3>Новое обращение</h3><form className="workspace-form" onSubmit={e=>{e.preventDefault();run("/api/me/support/tickets",{subject,message}).then(ok=>{if(ok){setSubject("");setMessage("")}})}}><label className="field">Тема<input required value={subject} onChange={e=>setSubject(e.target.value)} maxLength={255}/></label><label className="field">Сообщение<textarea required value={message} onChange={e=>setMessage(e.target.value)} maxLength={5000}/></label><button className="btn-primary" disabled={busy}>Отправить</button></form><h3>Мои обращения</h3>{!(data[0]||[]).length&&<p>Обращений пока нет.</p>}{(data[0]||[]).map((ticket:any)=><article className="workspace-record" key={ticket.id}><div><strong>#{ticket.id} · {ticket.subject}</strong><p>{ticket.message}</p><span>{label(ticket.status)} · {date(ticket.created_at)}</span>{ticket.admin_reply&&supportTicket!==ticket.id&&<div className="workspace-alert"><b>Последний ответ поддержки</b><p>{ticket.admin_reply}</p></div>}<button className="btn-ghost" onClick={()=>setSupportTicket(supportTicket===ticket.id?null:ticket.id)}>{supportTicket===ticket.id?"Закрыть переписку":"Открыть переписку"}</button>{supportTicket===ticket.id&&<SupportConversation key={ticket.id} ticketId={ticket.id} request={request} onStatusChange={status=>setData(prev=>[prev[0].map((row:any)=>row.id===ticket.id?{...row,status}:row)])}/>}</div></article>)}</>}
  </>}
 </div>;
}
function History({title,rows=[],columns}:{title:string;rows?:any[];columns:string[][]}){return <div className="workspace-history"><h3>{title}</h3><div className="table-scroll"><table><thead><tr>{columns.map(([key,title])=><th key={key}>{title}</th>)}</tr></thead><tbody>{rows.map((x,i)=><tr key={x.id||i}>{columns.map(([key])=><td key={key}>{key.endsWith("_at")?date(x[key]):key==="fulfillment_status"?({pending:"Ожидает выдачи",completed:"Выдан",failed:"Ошибка выдачи",processing:"Выдаётся"}[x[key]]||label(x[key])):key==="direction"?(x[key]==="credit"?"Начисление":"Списание"):label(String(x[key]??"—"))}</td>)}</tr>)}{!rows.length&&<tr><td colSpan={columns.length}>Операций пока нет</td></tr>}</tbody></table></div></div>}
